using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Model
{
	/// <summary>
	/// Strongly-typed collection for the TTempLineOrderPool class.
	/// </summary>
    [Serializable]
	public partial class TTempLineOrderPoolCollection : ActiveList<TTempLineOrderPool, TTempLineOrderPoolCollection>
	{	   
		public TTempLineOrderPoolCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TTempLineOrderPoolCollection</returns>
		public TTempLineOrderPoolCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TTempLineOrderPool o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the T_Temp_LineOrderPool table.
	/// </summary>
	[Serializable]
	public partial class TTempLineOrderPool : ActiveRecord<TTempLineOrderPool>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TTempLineOrderPool()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TTempLineOrderPool(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TTempLineOrderPool(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TTempLineOrderPool(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("T_Temp_LineOrderPool", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarKhdh = new TableSchema.TableColumn(schema);
				colvarKhdh.ColumnName = "Khdh";
				colvarKhdh.DataType = DbType.String;
				colvarKhdh.MaxLength = 50;
				colvarKhdh.AutoIncrement = false;
				colvarKhdh.IsNullable = false;
				colvarKhdh.IsPrimaryKey = true;
				colvarKhdh.IsForeignKey = false;
				colvarKhdh.IsReadOnly = false;
				colvarKhdh.DefaultSetting = @"";
				colvarKhdh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarKhdh);
				
				TableSchema.TableColumn colvarFzfl = new TableSchema.TableColumn(schema);
				colvarFzfl.ColumnName = "Fzfl";
				colvarFzfl.DataType = DbType.String;
				colvarFzfl.MaxLength = 50;
				colvarFzfl.AutoIncrement = false;
				colvarFzfl.IsNullable = false;
				colvarFzfl.IsPrimaryKey = true;
				colvarFzfl.IsForeignKey = false;
				colvarFzfl.IsReadOnly = false;
				colvarFzfl.DefaultSetting = @"";
				colvarFzfl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFzfl);
				
				TableSchema.TableColumn colvarLineName = new TableSchema.TableColumn(schema);
				colvarLineName.ColumnName = "LineName";
				colvarLineName.DataType = DbType.String;
				colvarLineName.MaxLength = 100;
				colvarLineName.AutoIncrement = false;
				colvarLineName.IsNullable = true;
				colvarLineName.IsPrimaryKey = false;
				colvarLineName.IsForeignKey = false;
				colvarLineName.IsReadOnly = false;
				colvarLineName.DefaultSetting = @"";
				colvarLineName.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLineName);
				
				TableSchema.TableColumn colvarNum = new TableSchema.TableColumn(schema);
				colvarNum.ColumnName = "Num";
				colvarNum.DataType = DbType.Int32;
				colvarNum.MaxLength = 0;
				colvarNum.AutoIncrement = false;
				colvarNum.IsNullable = true;
				colvarNum.IsPrimaryKey = false;
				colvarNum.IsForeignKey = false;
				colvarNum.IsReadOnly = false;
				colvarNum.DefaultSetting = @"";
				colvarNum.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNum);
				
				TableSchema.TableColumn colvarPlan = new TableSchema.TableColumn(schema);
				colvarPlan.ColumnName = "plan";
				colvarPlan.DataType = DbType.String;
				colvarPlan.MaxLength = 50;
				colvarPlan.AutoIncrement = false;
				colvarPlan.IsNullable = true;
				colvarPlan.IsPrimaryKey = false;
				colvarPlan.IsForeignKey = false;
				colvarPlan.IsReadOnly = false;
				colvarPlan.DefaultSetting = @"";
				colvarPlan.ForeignKeyTableName = "";
				schema.Columns.Add(colvarPlan);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("T_Temp_LineOrderPool",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Khdh")]
		[Bindable(true)]
		public string Khdh 
		{
			get { return GetColumnValue<string>(Columns.Khdh); }
			set { SetColumnValue(Columns.Khdh, value); }
		}
		  
		[XmlAttribute("Fzfl")]
		[Bindable(true)]
		public string Fzfl 
		{
			get { return GetColumnValue<string>(Columns.Fzfl); }
			set { SetColumnValue(Columns.Fzfl, value); }
		}
		  
		[XmlAttribute("LineName")]
		[Bindable(true)]
		public string LineName 
		{
			get { return GetColumnValue<string>(Columns.LineName); }
			set { SetColumnValue(Columns.LineName, value); }
		}
		  
		[XmlAttribute("Num")]
		[Bindable(true)]
		public int? Num 
		{
			get { return GetColumnValue<int?>(Columns.Num); }
			set { SetColumnValue(Columns.Num, value); }
		}
		  
		[XmlAttribute("Plan")]
		[Bindable(true)]
		public string Plan 
		{
			get { return GetColumnValue<string>(Columns.Plan); }
			set { SetColumnValue(Columns.Plan, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varKhdh,string varFzfl,string varLineName,int? varNum,string varPlan)
		{
			TTempLineOrderPool item = new TTempLineOrderPool();
			
			item.Khdh = varKhdh;
			
			item.Fzfl = varFzfl;
			
			item.LineName = varLineName;
			
			item.Num = varNum;
			
			item.Plan = varPlan;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varKhdh,string varFzfl,string varLineName,int? varNum,string varPlan)
		{
			TTempLineOrderPool item = new TTempLineOrderPool();
			
				item.Khdh = varKhdh;
			
				item.Fzfl = varFzfl;
			
				item.LineName = varLineName;
			
				item.Num = varNum;
			
				item.Plan = varPlan;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn KhdhColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn FzflColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LineNameColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn NumColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn PlanColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Khdh = @"Khdh";
			 public static string Fzfl = @"Fzfl";
			 public static string LineName = @"LineName";
			 public static string Num = @"Num";
			 public static string Plan = @"plan";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
