using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace APSData
{
	/// <summary>
	/// Strongly-typed collection for the TAPSCount class.
	/// </summary>
    [Serializable]
	public partial class TAPSCountCollection : ActiveList<TAPSCount, TAPSCountCollection>
	{	   
		public TAPSCountCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TAPSCountCollection</returns>
		public TAPSCountCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TAPSCount o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the T_APSCount table.
	/// </summary>
	[Serializable]
	public partial class TAPSCount : ActiveRecord<TAPSCount>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TAPSCount()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TAPSCount(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TAPSCount(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TAPSCount(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("T_APSCount", TableType.Table, DataService.GetInstance("Nowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarAPSFZCount = new TableSchema.TableColumn(schema);
				colvarAPSFZCount.ColumnName = "APSFZCount";
				colvarAPSFZCount.DataType = DbType.Int32;
				colvarAPSFZCount.MaxLength = 0;
				colvarAPSFZCount.AutoIncrement = false;
				colvarAPSFZCount.IsNullable = false;
				colvarAPSFZCount.IsPrimaryKey = true;
				colvarAPSFZCount.IsForeignKey = false;
				colvarAPSFZCount.IsReadOnly = false;
				colvarAPSFZCount.DefaultSetting = @"";
				colvarAPSFZCount.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAPSFZCount);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Nowthwin"].AddSchema("T_APSCount",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("APSFZCount")]
		[Bindable(true)]
		public int APSFZCount 
		{
			get { return GetColumnValue<int>(Columns.APSFZCount); }
			set { SetColumnValue(Columns.APSFZCount, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varAPSFZCount)
		{
			TAPSCount item = new TAPSCount();
			
			item.APSFZCount = varAPSFZCount;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varAPSFZCount)
		{
			TAPSCount item = new TAPSCount();
			
				item.APSFZCount = varAPSFZCount;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn APSFZCountColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string APSFZCount = @"APSFZCount";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
