using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Model{
    /// <summary>
    /// Strongly-typed collection for the ViewBomList class.
    /// </summary>
    [Serializable]
    public partial class ViewBomListCollection : ReadOnlyList<ViewBomList, ViewBomListCollection>
    {        
        public ViewBomListCollection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the ViewBomList view.
    /// </summary>
    [Serializable]
    public partial class ViewBomList : ReadOnlyRecord<ViewBomList>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("ViewBomList", TableType.View, DataService.GetInstance("Nowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"dbo";
                //columns
                
                TableSchema.TableColumn colvarResourcesName = new TableSchema.TableColumn(schema);
                colvarResourcesName.ColumnName = "resourcesName";
                colvarResourcesName.DataType = DbType.AnsiString;
                colvarResourcesName.MaxLength = 50;
                colvarResourcesName.AutoIncrement = false;
                colvarResourcesName.IsNullable = true;
                colvarResourcesName.IsPrimaryKey = false;
                colvarResourcesName.IsForeignKey = false;
                colvarResourcesName.IsReadOnly = false;
                
                schema.Columns.Add(colvarResourcesName);
                
                TableSchema.TableColumn colvarResource = new TableSchema.TableColumn(schema);
                colvarResource.ColumnName = "Resource";
                colvarResource.DataType = DbType.String;
                colvarResource.MaxLength = 250;
                colvarResource.AutoIncrement = false;
                colvarResource.IsNullable = true;
                colvarResource.IsPrimaryKey = false;
                colvarResource.IsForeignKey = false;
                colvarResource.IsReadOnly = false;
                
                schema.Columns.Add(colvarResource);
                
                TableSchema.TableColumn colvarProcode = new TableSchema.TableColumn(schema);
                colvarProcode.ColumnName = "Procode";
                colvarProcode.DataType = DbType.String;
                colvarProcode.MaxLength = 250;
                colvarProcode.AutoIncrement = false;
                colvarProcode.IsNullable = true;
                colvarProcode.IsPrimaryKey = false;
                colvarProcode.IsForeignKey = false;
                colvarProcode.IsReadOnly = false;
                
                schema.Columns.Add(colvarProcode);
                
                TableSchema.TableColumn colvarModeltype = new TableSchema.TableColumn(schema);
                colvarModeltype.ColumnName = "Modeltype";
                colvarModeltype.DataType = DbType.String;
                colvarModeltype.MaxLength = 250;
                colvarModeltype.AutoIncrement = false;
                colvarModeltype.IsNullable = true;
                colvarModeltype.IsPrimaryKey = false;
                colvarModeltype.IsForeignKey = false;
                colvarModeltype.IsReadOnly = false;
                
                schema.Columns.Add(colvarModeltype);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["Nowthwin"].AddSchema("ViewBomList",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public ViewBomList()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public ViewBomList(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public ViewBomList(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public ViewBomList(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("ResourcesName")]
        [Bindable(true)]
        public string ResourcesName 
	    {
		    get
		    {
			    return GetColumnValue<string>("resourcesName");
		    }
            set 
		    {
			    SetColumnValue("resourcesName", value);
            }
        }
	      
        [XmlAttribute("Resource")]
        [Bindable(true)]
        public string Resource 
	    {
		    get
		    {
			    return GetColumnValue<string>("Resource");
		    }
            set 
		    {
			    SetColumnValue("Resource", value);
            }
        }
	      
        [XmlAttribute("Procode")]
        [Bindable(true)]
        public string Procode 
	    {
		    get
		    {
			    return GetColumnValue<string>("Procode");
		    }
            set 
		    {
			    SetColumnValue("Procode", value);
            }
        }
	      
        [XmlAttribute("Modeltype")]
        [Bindable(true)]
        public string Modeltype 
	    {
		    get
		    {
			    return GetColumnValue<string>("Modeltype");
		    }
            set 
		    {
			    SetColumnValue("Modeltype", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string ResourcesName = @"resourcesName";
            
            public static string Resource = @"Resource";
            
            public static string Procode = @"Procode";
            
            public static string Modeltype = @"Modeltype";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
