using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Model
{
    /// <summary>
    /// Controller class for T_OrderArtInfo
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TOrderArtInfoController
    {
        // Preload our schema..
        TOrderArtInfo thisSchemaLoad = new TOrderArtInfo();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TOrderArtInfoCollection FetchAll()
        {
            TOrderArtInfoCollection coll = new TOrderArtInfoCollection();
            Query qry = new Query(TOrderArtInfo.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TOrderArtInfoCollection FetchByID(object OrderDetailID)
        {
            TOrderArtInfoCollection coll = new TOrderArtInfoCollection().Where("OrderDetailID", OrderDetailID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TOrderArtInfoCollection FetchByQuery(Query qry)
        {
            TOrderArtInfoCollection coll = new TOrderArtInfoCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object OrderDetailID)
        {
            return (TOrderArtInfo.Delete(OrderDetailID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object OrderDetailID)
        {
            return (TOrderArtInfo.Destroy(OrderDetailID) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string OrderDetailID,string Code)
        {
            Query qry = new Query(TOrderArtInfo.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("OrderDetailID", OrderDetailID).AND("Code", Code);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string OrderDetailID,string Code,string Hour,string OrderArtslist)
	    {
		    TOrderArtInfo item = new TOrderArtInfo();
		    
            item.OrderDetailID = OrderDetailID;
            
            item.Code = Code;
            
            item.Hour = Hour;
            
            item.OrderArtslist = OrderArtslist;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string OrderDetailID,string Code,string Hour,string OrderArtslist)
	    {
		    TOrderArtInfo item = new TOrderArtInfo();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.OrderDetailID = OrderDetailID;
				
			item.Code = Code;
				
			item.Hour = Hour;
				
			item.OrderArtslist = OrderArtslist;
				
	        item.Save(UserName);
	    }
    }
}
