using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for SCT272
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SCT272Controller
    {
        // Preload our schema..
        SCT272 thisSchemaLoad = new SCT272();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SCT272Collection FetchAll()
        {
            SCT272Collection coll = new SCT272Collection();
            Query qry = new Query(SCT272.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SCT272Collection FetchByID(object Sczsbh)
        {
            SCT272Collection coll = new SCT272Collection().Where("SCZSBH", Sczsbh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SCT272Collection FetchByQuery(Query qry)
        {
            SCT272Collection coll = new SCT272Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Sczsbh)
        {
            return (SCT272.Delete(Sczsbh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Sczsbh)
        {
            return (SCT272.Destroy(Sczsbh) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh)
        {
            Query qry = new Query(SCT272.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Sczsbh", Sczsbh).AND("Schtbh", Schtbh).AND("Xtwpks", Xtwpks).AND("Xtwpys", Xtwpys).AND("Xtxmdm", Xtxmdm).AND("Scptxh", Scptxh);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh,string Scptks,string Scptys,string Scptxm,decimal? Scptbl)
	    {
		    SCT272 item = new SCT272();
		    
            item.Sczsbh = Sczsbh;
            
            item.Schtbh = Schtbh;
            
            item.Xtwpks = Xtwpks;
            
            item.Xtwpys = Xtwpys;
            
            item.Xtxmdm = Xtxmdm;
            
            item.Scptxh = Scptxh;
            
            item.Scptks = Scptks;
            
            item.Scptys = Scptys;
            
            item.Scptxm = Scptxm;
            
            item.Scptbl = Scptbl;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh,string Scptks,string Scptys,string Scptxm,decimal? Scptbl)
	    {
		    SCT272 item = new SCT272();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Sczsbh = Sczsbh;
				
			item.Schtbh = Schtbh;
				
			item.Xtwpks = Xtwpks;
				
			item.Xtwpys = Xtwpys;
				
			item.Xtxmdm = Xtxmdm;
				
			item.Scptxh = Scptxh;
				
			item.Scptks = Scptks;
				
			item.Scptys = Scptys;
				
			item.Scptxm = Scptxm;
				
			item.Scptbl = Scptbl;
				
	        item.Save(UserName);
	    }
    }
}
