using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for SCT812
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SCT812Controller
    {
        // Preload our schema..
        SCT812 thisSchemaLoad = new SCT812();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SCT812Collection FetchAll()
        {
            SCT812Collection coll = new SCT812Collection();
            Query qry = new Query(SCT812.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SCT812Collection FetchByID(object Scsfbh)
        {
            SCT812Collection coll = new SCT812Collection().Where("SCSFBH", Scsfbh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SCT812Collection FetchByQuery(Query qry)
        {
            SCT812Collection coll = new SCT812Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Scsfbh)
        {
            return (SCT812.Delete(Scsfbh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Scsfbh)
        {
            return (SCT812.Destroy(Scsfbh) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Scsfbh,string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh)
        {
            Query qry = new Query(SCT812.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Scsfbh", Scsfbh).AND("Sczsbh", Sczsbh).AND("Schtbh", Schtbh).AND("Xtwpks", Xtwpks).AND("Xtwpys", Xtwpys).AND("Xtxmdm", Xtxmdm).AND("Scptxh", Scptxh);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Scsfbh,string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh,string Scptks,string Scptys,string Scptxm,decimal? Scptbl,string Sccpxh)
	    {
		    SCT812 item = new SCT812();
		    
            item.Scsfbh = Scsfbh;
            
            item.Sczsbh = Sczsbh;
            
            item.Schtbh = Schtbh;
            
            item.Xtwpks = Xtwpks;
            
            item.Xtwpys = Xtwpys;
            
            item.Xtxmdm = Xtxmdm;
            
            item.Scptxh = Scptxh;
            
            item.Scptks = Scptks;
            
            item.Scptys = Scptys;
            
            item.Scptxm = Scptxm;
            
            item.Scptbl = Scptbl;
            
            item.Sccpxh = Sccpxh;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Scsfbh,string Sczsbh,string Schtbh,string Xtwpks,string Xtwpys,string Xtxmdm,decimal Scptxh,string Scptks,string Scptys,string Scptxm,decimal? Scptbl,string Sccpxh)
	    {
		    SCT812 item = new SCT812();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Scsfbh = Scsfbh;
				
			item.Sczsbh = Sczsbh;
				
			item.Schtbh = Schtbh;
				
			item.Xtwpks = Xtwpks;
				
			item.Xtwpys = Xtwpys;
				
			item.Xtxmdm = Xtxmdm;
				
			item.Scptxh = Scptxh;
				
			item.Scptks = Scptks;
				
			item.Scptys = Scptys;
				
			item.Scptxm = Scptxm;
				
			item.Scptbl = Scptbl;
				
			item.Sccpxh = Sccpxh;
				
	        item.Save(UserName);
	    }
    }
}
