using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
	/// <summary>
	/// Strongly-typed collection for the SCT96 class.
	/// </summary>
    [Serializable]
	public partial class SCT96Collection : ActiveList<SCT96, SCT96Collection>
	{	   
		public SCT96Collection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>SCT96Collection</returns>
		public SCT96Collection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                SCT96 o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the SCT96 table.
	/// </summary>
	[Serializable]
	public partial class SCT96 : ActiveRecord<SCT96>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public SCT96()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public SCT96(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public SCT96(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public SCT96(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("SCT96", TableType.Table, DataService.GetInstance("ErpNowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"FYERP";
				//columns
				
				TableSchema.TableColumn colvarSclldh = new TableSchema.TableColumn(schema);
				colvarSclldh.ColumnName = "SCLLDH";
				colvarSclldh.DataType = DbType.String;
				colvarSclldh.MaxLength = 12;
				colvarSclldh.AutoIncrement = false;
				colvarSclldh.IsNullable = false;
				colvarSclldh.IsPrimaryKey = true;
				colvarSclldh.IsForeignKey = false;
				colvarSclldh.IsReadOnly = false;
				colvarSclldh.DefaultSetting = @"";
				colvarSclldh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSclldh);
				
				TableSchema.TableColumn colvarScsmxh = new TableSchema.TableColumn(schema);
				colvarScsmxh.ColumnName = "SCSMXH";
				colvarScsmxh.DataType = DbType.Decimal;
				colvarScsmxh.MaxLength = 0;
				colvarScsmxh.AutoIncrement = false;
				colvarScsmxh.IsNullable = false;
				colvarScsmxh.IsPrimaryKey = true;
				colvarScsmxh.IsForeignKey = false;
				colvarScsmxh.IsReadOnly = false;
				colvarScsmxh.DefaultSetting = @"";
				colvarScsmxh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarScsmxh);
				
				TableSchema.TableColumn colvarScsmnr = new TableSchema.TableColumn(schema);
				colvarScsmnr.ColumnName = "SCSMNR";
				colvarScsmnr.DataType = DbType.String;
				colvarScsmnr.MaxLength = 255;
				colvarScsmnr.AutoIncrement = false;
				colvarScsmnr.IsNullable = true;
				colvarScsmnr.IsPrimaryKey = false;
				colvarScsmnr.IsForeignKey = false;
				colvarScsmnr.IsReadOnly = false;
				colvarScsmnr.DefaultSetting = @"";
				colvarScsmnr.ForeignKeyTableName = "";
				schema.Columns.Add(colvarScsmnr);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["ErpNowthwin"].AddSchema("SCT96",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Sclldh")]
		[Bindable(true)]
		public string Sclldh 
		{
			get { return GetColumnValue<string>(Columns.Sclldh); }
			set { SetColumnValue(Columns.Sclldh, value); }
		}
		  
		[XmlAttribute("Scsmxh")]
		[Bindable(true)]
		public decimal Scsmxh 
		{
			get { return GetColumnValue<decimal>(Columns.Scsmxh); }
			set { SetColumnValue(Columns.Scsmxh, value); }
		}
		  
		[XmlAttribute("Scsmnr")]
		[Bindable(true)]
		public string Scsmnr 
		{
			get { return GetColumnValue<string>(Columns.Scsmnr); }
			set { SetColumnValue(Columns.Scsmnr, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varSclldh,decimal varScsmxh,string varScsmnr)
		{
			SCT96 item = new SCT96();
			
			item.Sclldh = varSclldh;
			
			item.Scsmxh = varScsmxh;
			
			item.Scsmnr = varScsmnr;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varSclldh,decimal varScsmxh,string varScsmnr)
		{
			SCT96 item = new SCT96();
			
				item.Sclldh = varSclldh;
			
				item.Scsmxh = varScsmxh;
			
				item.Scsmnr = varScsmnr;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn SclldhColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ScsmxhColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ScsmnrColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Sclldh = @"SCLLDH";
			 public static string Scsmxh = @"SCSMXH";
			 public static string Scsmnr = @"SCSMNR";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
