using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for SLAUTHORITY
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class SlauthorityController
    {
        // Preload our schema..
        Slauthority thisSchemaLoad = new Slauthority();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public SlauthorityCollection FetchAll()
        {
            SlauthorityCollection coll = new SlauthorityCollection();
            Query qry = new Query(Slauthority.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public SlauthorityCollection FetchByID(object Userid)
        {
            SlauthorityCollection coll = new SlauthorityCollection().Where("USERID", Userid).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public SlauthorityCollection FetchByQuery(Query qry)
        {
            SlauthorityCollection coll = new SlauthorityCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Userid)
        {
            return (Slauthority.Delete(Userid) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Userid)
        {
            return (Slauthority.Destroy(Userid) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Userid,string Vdll,string Vdspno)
        {
            Query qry = new Query(Slauthority.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Userid", Userid).AND("Vdll", Vdll).AND("Vdspno", Vdspno);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Id,string Userid,string Vdll,string Vdspno,string Ifdeleted,DateTime? Createdate,DateTime? Updatedate,string Username,string Createuser,string Updateuser)
	    {
		    Slauthority item = new Slauthority();
		    
            item.Id = Id;
            
            item.Userid = Userid;
            
            item.Vdll = Vdll;
            
            item.Vdspno = Vdspno;
            
            item.Ifdeleted = Ifdeleted;
            
            item.Createdate = Createdate;
            
            item.Updatedate = Updatedate;
            
            item.Username = Username;
            
            item.Createuser = Createuser;
            
            item.Updateuser = Updateuser;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Id,string Userid,string Vdll,string Vdspno,string Ifdeleted,DateTime? Createdate,DateTime? Updatedate,string Username,string Createuser,string Updateuser)
	    {
		    Slauthority item = new Slauthority();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Id = Id;
				
			item.Userid = Userid;
				
			item.Vdll = Vdll;
				
			item.Vdspno = Vdspno;
				
			item.Ifdeleted = Ifdeleted;
				
			item.Createdate = Createdate;
				
			item.Updatedate = Updatedate;
				
			item.Username = Username;
				
			item.Createuser = Createuser;
				
			item.Updateuser = Updateuser;
				
	        item.Save(UserName);
	    }
    }
}
