using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain{
    /// <summary>
    /// Strongly-typed collection for the VCWT02 class.
    /// </summary>
    [Serializable]
    public partial class VCWT02Collection : ReadOnlyList<VCWT02, VCWT02Collection>
    {        
        public VCWT02Collection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the V_CWT02 view.
    /// </summary>
    [Serializable]
    public partial class VCWT02 : ReadOnlyRecord<VCWT02>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("V_CWT02", TableType.View, DataService.GetInstance("ErpNowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"FYERP";
                //columns
                
                TableSchema.TableColumn colvarNbpzhh = new TableSchema.TableColumn(schema);
                colvarNbpzhh.ColumnName = "NBPZHH";
                colvarNbpzhh.DataType = DbType.Decimal;
                colvarNbpzhh.MaxLength = 0;
                colvarNbpzhh.AutoIncrement = false;
                colvarNbpzhh.IsNullable = false;
                colvarNbpzhh.IsPrimaryKey = false;
                colvarNbpzhh.IsForeignKey = false;
                colvarNbpzhh.IsReadOnly = false;
                
                schema.Columns.Add(colvarNbpzhh);
                
                TableSchema.TableColumn colvarCwkjnd = new TableSchema.TableColumn(schema);
                colvarCwkjnd.ColumnName = "CWKJND";
                colvarCwkjnd.DataType = DbType.Decimal;
                colvarCwkjnd.MaxLength = 0;
                colvarCwkjnd.AutoIncrement = false;
                colvarCwkjnd.IsNullable = false;
                colvarCwkjnd.IsPrimaryKey = false;
                colvarCwkjnd.IsForeignKey = false;
                colvarCwkjnd.IsReadOnly = false;
                
                schema.Columns.Add(colvarCwkjnd);
                
                TableSchema.TableColumn colvarPzzh = new TableSchema.TableColumn(schema);
                colvarPzzh.ColumnName = "PZZH";
                colvarPzzh.DataType = DbType.Decimal;
                colvarPzzh.MaxLength = 0;
                colvarPzzh.AutoIncrement = false;
                colvarPzzh.IsNullable = true;
                colvarPzzh.IsPrimaryKey = false;
                colvarPzzh.IsForeignKey = false;
                colvarPzzh.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzzh);
                
                TableSchema.TableColumn colvarPzhm = new TableSchema.TableColumn(schema);
                colvarPzhm.ColumnName = "PZHM";
                colvarPzhm.DataType = DbType.String;
                colvarPzhm.MaxLength = 8;
                colvarPzhm.AutoIncrement = false;
                colvarPzhm.IsNullable = true;
                colvarPzhm.IsPrimaryKey = false;
                colvarPzhm.IsForeignKey = false;
                colvarPzhm.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzhm);
                
                TableSchema.TableColumn colvarPzrq = new TableSchema.TableColumn(schema);
                colvarPzrq.ColumnName = "PZRQ";
                colvarPzrq.DataType = DbType.DateTime;
                colvarPzrq.MaxLength = 0;
                colvarPzrq.AutoIncrement = false;
                colvarPzrq.IsNullable = true;
                colvarPzrq.IsPrimaryKey = false;
                colvarPzrq.IsForeignKey = false;
                colvarPzrq.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzrq);
                
                TableSchema.TableColumn colvarPzlbdm = new TableSchema.TableColumn(schema);
                colvarPzlbdm.ColumnName = "PZLBDM";
                colvarPzlbdm.DataType = DbType.String;
                colvarPzlbdm.MaxLength = 2;
                colvarPzlbdm.AutoIncrement = false;
                colvarPzlbdm.IsNullable = true;
                colvarPzlbdm.IsPrimaryKey = false;
                colvarPzlbdm.IsForeignKey = false;
                colvarPzlbdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzlbdm);
                
                TableSchema.TableColumn colvarWbpzbz = new TableSchema.TableColumn(schema);
                colvarWbpzbz.ColumnName = "WBPZBZ";
                colvarWbpzbz.DataType = DbType.String;
                colvarWbpzbz.MaxLength = 1;
                colvarWbpzbz.AutoIncrement = false;
                colvarWbpzbz.IsNullable = true;
                colvarWbpzbz.IsPrimaryKey = false;
                colvarWbpzbz.IsForeignKey = false;
                colvarWbpzbz.IsReadOnly = false;
                
                schema.Columns.Add(colvarWbpzbz);
                
                TableSchema.TableColumn colvarPzclbz = new TableSchema.TableColumn(schema);
                colvarPzclbz.ColumnName = "PZCLBZ";
                colvarPzclbz.DataType = DbType.String;
                colvarPzclbz.MaxLength = 1;
                colvarPzclbz.AutoIncrement = false;
                colvarPzclbz.IsNullable = true;
                colvarPzclbz.IsPrimaryKey = false;
                colvarPzclbz.IsForeignKey = false;
                colvarPzclbz.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzclbz);
                
                TableSchema.TableColumn colvarPzzfbz = new TableSchema.TableColumn(schema);
                colvarPzzfbz.ColumnName = "PZZFBZ";
                colvarPzzfbz.DataType = DbType.String;
                colvarPzzfbz.MaxLength = 1;
                colvarPzzfbz.AutoIncrement = false;
                colvarPzzfbz.IsNullable = true;
                colvarPzzfbz.IsPrimaryKey = false;
                colvarPzzfbz.IsForeignKey = false;
                colvarPzzfbz.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzzfbz);
                
                TableSchema.TableColumn colvarCwshry = new TableSchema.TableColumn(schema);
                colvarCwshry.ColumnName = "CWSHRY";
                colvarCwshry.DataType = DbType.String;
                colvarCwshry.MaxLength = 8;
                colvarCwshry.AutoIncrement = false;
                colvarCwshry.IsNullable = true;
                colvarCwshry.IsPrimaryKey = false;
                colvarCwshry.IsForeignKey = false;
                colvarCwshry.IsReadOnly = false;
                
                schema.Columns.Add(colvarCwshry);
                
                TableSchema.TableColumn colvarCwlrry = new TableSchema.TableColumn(schema);
                colvarCwlrry.ColumnName = "CWLRRY";
                colvarCwlrry.DataType = DbType.String;
                colvarCwlrry.MaxLength = 8;
                colvarCwlrry.AutoIncrement = false;
                colvarCwlrry.IsNullable = true;
                colvarCwlrry.IsPrimaryKey = false;
                colvarCwlrry.IsForeignKey = false;
                colvarCwlrry.IsReadOnly = false;
                
                schema.Columns.Add(colvarCwlrry);
                
                TableSchema.TableColumn colvarCwjzry = new TableSchema.TableColumn(schema);
                colvarCwjzry.ColumnName = "CWJZRY";
                colvarCwjzry.DataType = DbType.String;
                colvarCwjzry.MaxLength = 8;
                colvarCwjzry.AutoIncrement = false;
                colvarCwjzry.IsNullable = true;
                colvarCwjzry.IsPrimaryKey = false;
                colvarCwjzry.IsForeignKey = false;
                colvarCwjzry.IsReadOnly = false;
                
                schema.Columns.Add(colvarCwjzry);
                
                TableSchema.TableColumn colvarCwxgry = new TableSchema.TableColumn(schema);
                colvarCwxgry.ColumnName = "CWXGRY";
                colvarCwxgry.DataType = DbType.String;
                colvarCwxgry.MaxLength = 8;
                colvarCwxgry.AutoIncrement = false;
                colvarCwxgry.IsNullable = true;
                colvarCwxgry.IsPrimaryKey = false;
                colvarCwxgry.IsForeignKey = false;
                colvarCwxgry.IsReadOnly = false;
                
                schema.Columns.Add(colvarCwxgry);
                
                TableSchema.TableColumn colvarPzlydm = new TableSchema.TableColumn(schema);
                colvarPzlydm.ColumnName = "PZLYDM";
                colvarPzlydm.DataType = DbType.String;
                colvarPzlydm.MaxLength = 3;
                colvarPzlydm.AutoIncrement = false;
                colvarPzlydm.IsNullable = true;
                colvarPzlydm.IsPrimaryKey = false;
                colvarPzlydm.IsForeignKey = false;
                colvarPzlydm.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzlydm);
                
                TableSchema.TableColumn colvarPzfdjs = new TableSchema.TableColumn(schema);
                colvarPzfdjs.ColumnName = "PZFDJS";
                colvarPzfdjs.DataType = DbType.Decimal;
                colvarPzfdjs.MaxLength = 0;
                colvarPzfdjs.AutoIncrement = false;
                colvarPzfdjs.IsNullable = true;
                colvarPzfdjs.IsPrimaryKey = false;
                colvarPzfdjs.IsForeignKey = false;
                colvarPzfdjs.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzfdjs);
                
                TableSchema.TableColumn colvarPzflnm = new TableSchema.TableColumn(schema);
                colvarPzflnm.ColumnName = "PZFLNM";
                colvarPzflnm.DataType = DbType.Decimal;
                colvarPzflnm.MaxLength = 0;
                colvarPzflnm.AutoIncrement = false;
                colvarPzflnm.IsNullable = false;
                colvarPzflnm.IsPrimaryKey = false;
                colvarPzflnm.IsForeignKey = false;
                colvarPzflnm.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzflnm);
                
                TableSchema.TableColumn colvarKmdm = new TableSchema.TableColumn(schema);
                colvarKmdm.ColumnName = "KMDM";
                colvarKmdm.DataType = DbType.String;
                colvarKmdm.MaxLength = 15;
                colvarKmdm.AutoIncrement = false;
                colvarKmdm.IsNullable = true;
                colvarKmdm.IsPrimaryKey = false;
                colvarKmdm.IsForeignKey = false;
                colvarKmdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarKmdm);
                
                TableSchema.TableColumn colvarXthbdm = new TableSchema.TableColumn(schema);
                colvarXthbdm.ColumnName = "XTHBDM";
                colvarXthbdm.DataType = DbType.String;
                colvarXthbdm.MaxLength = 3;
                colvarXthbdm.AutoIncrement = false;
                colvarXthbdm.IsNullable = true;
                colvarXthbdm.IsPrimaryKey = false;
                colvarXthbdm.IsForeignKey = false;
                colvarXthbdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarXthbdm);
                
                TableSchema.TableColumn colvarPzzy = new TableSchema.TableColumn(schema);
                colvarPzzy.ColumnName = "PZZY";
                colvarPzzy.DataType = DbType.String;
                colvarPzzy.MaxLength = 120;
                colvarPzzy.AutoIncrement = false;
                colvarPzzy.IsNullable = true;
                colvarPzzy.IsPrimaryKey = false;
                colvarPzzy.IsForeignKey = false;
                colvarPzzy.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzzy);
                
                TableSchema.TableColumn colvarKmjdfx = new TableSchema.TableColumn(schema);
                colvarKmjdfx.ColumnName = "KMJDFX";
                colvarKmjdfx.DataType = DbType.String;
                colvarKmjdfx.MaxLength = 1;
                colvarKmjdfx.AutoIncrement = false;
                colvarKmjdfx.IsNullable = true;
                colvarKmjdfx.IsPrimaryKey = false;
                colvarKmjdfx.IsForeignKey = false;
                colvarKmjdfx.IsReadOnly = false;
                
                schema.Columns.Add(colvarKmjdfx);
                
                TableSchema.TableColumn colvarFlybje = new TableSchema.TableColumn(schema);
                colvarFlybje.ColumnName = "FLYBJE";
                colvarFlybje.DataType = DbType.Decimal;
                colvarFlybje.MaxLength = 0;
                colvarFlybje.AutoIncrement = false;
                colvarFlybje.IsNullable = true;
                colvarFlybje.IsPrimaryKey = false;
                colvarFlybje.IsForeignKey = false;
                colvarFlybje.IsReadOnly = false;
                
                schema.Columns.Add(colvarFlybje);
                
                TableSchema.TableColumn colvarFlbbje = new TableSchema.TableColumn(schema);
                colvarFlbbje.ColumnName = "FLBBJE";
                colvarFlbbje.DataType = DbType.Decimal;
                colvarFlbbje.MaxLength = 0;
                colvarFlbbje.AutoIncrement = false;
                colvarFlbbje.IsNullable = true;
                colvarFlbbje.IsPrimaryKey = false;
                colvarFlbbje.IsForeignKey = false;
                colvarFlbbje.IsReadOnly = false;
                
                schema.Columns.Add(colvarFlbbje);
                
                TableSchema.TableColumn colvarHl = new TableSchema.TableColumn(schema);
                colvarHl.ColumnName = "HL";
                colvarHl.DataType = DbType.Decimal;
                colvarHl.MaxLength = 0;
                colvarHl.AutoIncrement = false;
                colvarHl.IsNullable = true;
                colvarHl.IsPrimaryKey = false;
                colvarHl.IsForeignKey = false;
                colvarHl.IsReadOnly = false;
                
                schema.Columns.Add(colvarHl);
                
                TableSchema.TableColumn colvarPzflsl = new TableSchema.TableColumn(schema);
                colvarPzflsl.ColumnName = "PZFLSL";
                colvarPzflsl.DataType = DbType.Decimal;
                colvarPzflsl.MaxLength = 0;
                colvarPzflsl.AutoIncrement = false;
                colvarPzflsl.IsNullable = true;
                colvarPzflsl.IsPrimaryKey = false;
                colvarPzflsl.IsForeignKey = false;
                colvarPzflsl.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzflsl);
                
                TableSchema.TableColumn colvarXtjsfs = new TableSchema.TableColumn(schema);
                colvarXtjsfs.ColumnName = "XTJSFS";
                colvarXtjsfs.DataType = DbType.String;
                colvarXtjsfs.MaxLength = 4;
                colvarXtjsfs.AutoIncrement = false;
                colvarXtjsfs.IsNullable = true;
                colvarXtjsfs.IsPrimaryKey = false;
                colvarXtjsfs.IsForeignKey = false;
                colvarXtjsfs.IsReadOnly = false;
                
                schema.Columns.Add(colvarXtjsfs);
                
                TableSchema.TableColumn colvarJsdhm = new TableSchema.TableColumn(schema);
                colvarJsdhm.ColumnName = "JSDHM";
                colvarJsdhm.DataType = DbType.String;
                colvarJsdhm.MaxLength = 20;
                colvarJsdhm.AutoIncrement = false;
                colvarJsdhm.IsNullable = true;
                colvarJsdhm.IsPrimaryKey = false;
                colvarJsdhm.IsForeignKey = false;
                colvarJsdhm.IsReadOnly = false;
                
                schema.Columns.Add(colvarJsdhm);
                
                TableSchema.TableColumn colvarJsrq = new TableSchema.TableColumn(schema);
                colvarJsrq.ColumnName = "JSRQ";
                colvarJsrq.DataType = DbType.DateTime;
                colvarJsrq.MaxLength = 0;
                colvarJsrq.AutoIncrement = false;
                colvarJsrq.IsNullable = true;
                colvarJsrq.IsPrimaryKey = false;
                colvarJsrq.IsForeignKey = false;
                colvarJsrq.IsReadOnly = false;
                
                schema.Columns.Add(colvarJsrq);
                
                TableSchema.TableColumn colvarYsdzhm = new TableSchema.TableColumn(schema);
                colvarYsdzhm.ColumnName = "YSDZHM";
                colvarYsdzhm.DataType = DbType.String;
                colvarYsdzhm.MaxLength = 20;
                colvarYsdzhm.AutoIncrement = false;
                colvarYsdzhm.IsNullable = true;
                colvarYsdzhm.IsPrimaryKey = false;
                colvarYsdzhm.IsForeignKey = false;
                colvarYsdzhm.IsReadOnly = false;
                
                schema.Columns.Add(colvarYsdzhm);
                
                TableSchema.TableColumn colvarXtjldw = new TableSchema.TableColumn(schema);
                colvarXtjldw.ColumnName = "XTJLDW";
                colvarXtjldw.DataType = DbType.String;
                colvarXtjldw.MaxLength = 6;
                colvarXtjldw.AutoIncrement = false;
                colvarXtjldw.IsNullable = true;
                colvarXtjldw.IsPrimaryKey = false;
                colvarXtjldw.IsForeignKey = false;
                colvarXtjldw.IsReadOnly = false;
                
                schema.Columns.Add(colvarXtjldw);
                
                TableSchema.TableColumn colvarPzflxh = new TableSchema.TableColumn(schema);
                colvarPzflxh.ColumnName = "PZFLXH";
                colvarPzflxh.DataType = DbType.Decimal;
                colvarPzflxh.MaxLength = 0;
                colvarPzflxh.AutoIncrement = false;
                colvarPzflxh.IsNullable = true;
                colvarPzflxh.IsPrimaryKey = false;
                colvarPzflxh.IsForeignKey = false;
                colvarPzflxh.IsReadOnly = false;
                
                schema.Columns.Add(colvarPzflxh);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["ErpNowthwin"].AddSchema("V_CWT02",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VCWT02()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public VCWT02(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public VCWT02(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public VCWT02(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Nbpzhh")]
        [Bindable(true)]
        public decimal Nbpzhh 
	    {
		    get
		    {
			    return GetColumnValue<decimal>("NBPZHH");
		    }
            set 
		    {
			    SetColumnValue("NBPZHH", value);
            }
        }
	      
        [XmlAttribute("Cwkjnd")]
        [Bindable(true)]
        public decimal Cwkjnd 
	    {
		    get
		    {
			    return GetColumnValue<decimal>("CWKJND");
		    }
            set 
		    {
			    SetColumnValue("CWKJND", value);
            }
        }
	      
        [XmlAttribute("Pzzh")]
        [Bindable(true)]
        public decimal? Pzzh 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("PZZH");
		    }
            set 
		    {
			    SetColumnValue("PZZH", value);
            }
        }
	      
        [XmlAttribute("Pzhm")]
        [Bindable(true)]
        public string Pzhm 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZHM");
		    }
            set 
		    {
			    SetColumnValue("PZHM", value);
            }
        }
	      
        [XmlAttribute("Pzrq")]
        [Bindable(true)]
        public DateTime? Pzrq 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("PZRQ");
		    }
            set 
		    {
			    SetColumnValue("PZRQ", value);
            }
        }
	      
        [XmlAttribute("Pzlbdm")]
        [Bindable(true)]
        public string Pzlbdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZLBDM");
		    }
            set 
		    {
			    SetColumnValue("PZLBDM", value);
            }
        }
	      
        [XmlAttribute("Wbpzbz")]
        [Bindable(true)]
        public string Wbpzbz 
	    {
		    get
		    {
			    return GetColumnValue<string>("WBPZBZ");
		    }
            set 
		    {
			    SetColumnValue("WBPZBZ", value);
            }
        }
	      
        [XmlAttribute("Pzclbz")]
        [Bindable(true)]
        public string Pzclbz 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZCLBZ");
		    }
            set 
		    {
			    SetColumnValue("PZCLBZ", value);
            }
        }
	      
        [XmlAttribute("Pzzfbz")]
        [Bindable(true)]
        public string Pzzfbz 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZZFBZ");
		    }
            set 
		    {
			    SetColumnValue("PZZFBZ", value);
            }
        }
	      
        [XmlAttribute("Cwshry")]
        [Bindable(true)]
        public string Cwshry 
	    {
		    get
		    {
			    return GetColumnValue<string>("CWSHRY");
		    }
            set 
		    {
			    SetColumnValue("CWSHRY", value);
            }
        }
	      
        [XmlAttribute("Cwlrry")]
        [Bindable(true)]
        public string Cwlrry 
	    {
		    get
		    {
			    return GetColumnValue<string>("CWLRRY");
		    }
            set 
		    {
			    SetColumnValue("CWLRRY", value);
            }
        }
	      
        [XmlAttribute("Cwjzry")]
        [Bindable(true)]
        public string Cwjzry 
	    {
		    get
		    {
			    return GetColumnValue<string>("CWJZRY");
		    }
            set 
		    {
			    SetColumnValue("CWJZRY", value);
            }
        }
	      
        [XmlAttribute("Cwxgry")]
        [Bindable(true)]
        public string Cwxgry 
	    {
		    get
		    {
			    return GetColumnValue<string>("CWXGRY");
		    }
            set 
		    {
			    SetColumnValue("CWXGRY", value);
            }
        }
	      
        [XmlAttribute("Pzlydm")]
        [Bindable(true)]
        public string Pzlydm 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZLYDM");
		    }
            set 
		    {
			    SetColumnValue("PZLYDM", value);
            }
        }
	      
        [XmlAttribute("Pzfdjs")]
        [Bindable(true)]
        public decimal? Pzfdjs 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("PZFDJS");
		    }
            set 
		    {
			    SetColumnValue("PZFDJS", value);
            }
        }
	      
        [XmlAttribute("Pzflnm")]
        [Bindable(true)]
        public decimal Pzflnm 
	    {
		    get
		    {
			    return GetColumnValue<decimal>("PZFLNM");
		    }
            set 
		    {
			    SetColumnValue("PZFLNM", value);
            }
        }
	      
        [XmlAttribute("Kmdm")]
        [Bindable(true)]
        public string Kmdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("KMDM");
		    }
            set 
		    {
			    SetColumnValue("KMDM", value);
            }
        }
	      
        [XmlAttribute("Xthbdm")]
        [Bindable(true)]
        public string Xthbdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("XTHBDM");
		    }
            set 
		    {
			    SetColumnValue("XTHBDM", value);
            }
        }
	      
        [XmlAttribute("Pzzy")]
        [Bindable(true)]
        public string Pzzy 
	    {
		    get
		    {
			    return GetColumnValue<string>("PZZY");
		    }
            set 
		    {
			    SetColumnValue("PZZY", value);
            }
        }
	      
        [XmlAttribute("Kmjdfx")]
        [Bindable(true)]
        public string Kmjdfx 
	    {
		    get
		    {
			    return GetColumnValue<string>("KMJDFX");
		    }
            set 
		    {
			    SetColumnValue("KMJDFX", value);
            }
        }
	      
        [XmlAttribute("Flybje")]
        [Bindable(true)]
        public decimal? Flybje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("FLYBJE");
		    }
            set 
		    {
			    SetColumnValue("FLYBJE", value);
            }
        }
	      
        [XmlAttribute("Flbbje")]
        [Bindable(true)]
        public decimal? Flbbje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("FLBBJE");
		    }
            set 
		    {
			    SetColumnValue("FLBBJE", value);
            }
        }
	      
        [XmlAttribute("Hl")]
        [Bindable(true)]
        public decimal? Hl 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("HL");
		    }
            set 
		    {
			    SetColumnValue("HL", value);
            }
        }
	      
        [XmlAttribute("Pzflsl")]
        [Bindable(true)]
        public decimal? Pzflsl 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("PZFLSL");
		    }
            set 
		    {
			    SetColumnValue("PZFLSL", value);
            }
        }
	      
        [XmlAttribute("Xtjsfs")]
        [Bindable(true)]
        public string Xtjsfs 
	    {
		    get
		    {
			    return GetColumnValue<string>("XTJSFS");
		    }
            set 
		    {
			    SetColumnValue("XTJSFS", value);
            }
        }
	      
        [XmlAttribute("Jsdhm")]
        [Bindable(true)]
        public string Jsdhm 
	    {
		    get
		    {
			    return GetColumnValue<string>("JSDHM");
		    }
            set 
		    {
			    SetColumnValue("JSDHM", value);
            }
        }
	      
        [XmlAttribute("Jsrq")]
        [Bindable(true)]
        public DateTime? Jsrq 
	    {
		    get
		    {
			    return GetColumnValue<DateTime?>("JSRQ");
		    }
            set 
		    {
			    SetColumnValue("JSRQ", value);
            }
        }
	      
        [XmlAttribute("Ysdzhm")]
        [Bindable(true)]
        public string Ysdzhm 
	    {
		    get
		    {
			    return GetColumnValue<string>("YSDZHM");
		    }
            set 
		    {
			    SetColumnValue("YSDZHM", value);
            }
        }
	      
        [XmlAttribute("Xtjldw")]
        [Bindable(true)]
        public string Xtjldw 
	    {
		    get
		    {
			    return GetColumnValue<string>("XTJLDW");
		    }
            set 
		    {
			    SetColumnValue("XTJLDW", value);
            }
        }
	      
        [XmlAttribute("Pzflxh")]
        [Bindable(true)]
        public decimal? Pzflxh 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("PZFLXH");
		    }
            set 
		    {
			    SetColumnValue("PZFLXH", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Nbpzhh = @"NBPZHH";
            
            public static string Cwkjnd = @"CWKJND";
            
            public static string Pzzh = @"PZZH";
            
            public static string Pzhm = @"PZHM";
            
            public static string Pzrq = @"PZRQ";
            
            public static string Pzlbdm = @"PZLBDM";
            
            public static string Wbpzbz = @"WBPZBZ";
            
            public static string Pzclbz = @"PZCLBZ";
            
            public static string Pzzfbz = @"PZZFBZ";
            
            public static string Cwshry = @"CWSHRY";
            
            public static string Cwlrry = @"CWLRRY";
            
            public static string Cwjzry = @"CWJZRY";
            
            public static string Cwxgry = @"CWXGRY";
            
            public static string Pzlydm = @"PZLYDM";
            
            public static string Pzfdjs = @"PZFDJS";
            
            public static string Pzflnm = @"PZFLNM";
            
            public static string Kmdm = @"KMDM";
            
            public static string Xthbdm = @"XTHBDM";
            
            public static string Pzzy = @"PZZY";
            
            public static string Kmjdfx = @"KMJDFX";
            
            public static string Flybje = @"FLYBJE";
            
            public static string Flbbje = @"FLBBJE";
            
            public static string Hl = @"HL";
            
            public static string Pzflsl = @"PZFLSL";
            
            public static string Xtjsfs = @"XTJSFS";
            
            public static string Jsdhm = @"JSDHM";
            
            public static string Jsrq = @"JSRQ";
            
            public static string Ysdzhm = @"YSDZHM";
            
            public static string Xtjldw = @"XTJLDW";
            
            public static string Pzflxh = @"PZFLXH";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
