using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain{
    /// <summary>
    /// Strongly-typed collection for the VKCT06 class.
    /// </summary>
    [Serializable]
    public partial class VKCT06Collection : ReadOnlyList<VKCT06, VKCT06Collection>
    {        
        public VKCT06Collection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the V_KCT06 view.
    /// </summary>
    [Serializable]
    public partial class VKCT06 : ReadOnlyRecord<VKCT06>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("V_KCT06", TableType.View, DataService.GetInstance("ErpNowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"FYERP";
                //columns
                
                TableSchema.TableColumn colvarKckjnd = new TableSchema.TableColumn(schema);
                colvarKckjnd.ColumnName = "KCKJND";
                colvarKckjnd.DataType = DbType.Decimal;
                colvarKckjnd.MaxLength = 0;
                colvarKckjnd.AutoIncrement = false;
                colvarKckjnd.IsNullable = false;
                colvarKckjnd.IsPrimaryKey = false;
                colvarKckjnd.IsForeignKey = false;
                colvarKckjnd.IsReadOnly = false;
                
                schema.Columns.Add(colvarKckjnd);
                
                TableSchema.TableColumn colvarKckjyf = new TableSchema.TableColumn(schema);
                colvarKckjyf.ColumnName = "KCKJYF";
                colvarKckjyf.DataType = DbType.Decimal;
                colvarKckjyf.MaxLength = 0;
                colvarKckjyf.AutoIncrement = false;
                colvarKckjyf.IsNullable = false;
                colvarKckjyf.IsPrimaryKey = false;
                colvarKckjyf.IsForeignKey = false;
                colvarKckjyf.IsReadOnly = false;
                
                schema.Columns.Add(colvarKckjyf);
                
                TableSchema.TableColumn colvarKcckdm = new TableSchema.TableColumn(schema);
                colvarKcckdm.ColumnName = "KCCKDM";
                colvarKcckdm.DataType = DbType.String;
                colvarKcckdm.MaxLength = 8;
                colvarKcckdm.AutoIncrement = false;
                colvarKcckdm.IsNullable = false;
                colvarKcckdm.IsPrimaryKey = false;
                colvarKcckdm.IsForeignKey = false;
                colvarKcckdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcckdm);
                
                TableSchema.TableColumn colvarXtwpdm = new TableSchema.TableColumn(schema);
                colvarXtwpdm.ColumnName = "XTWPDM";
                colvarXtwpdm.DataType = DbType.String;
                colvarXtwpdm.MaxLength = 20;
                colvarXtwpdm.AutoIncrement = false;
                colvarXtwpdm.IsNullable = false;
                colvarXtwpdm.IsPrimaryKey = false;
                colvarXtwpdm.IsForeignKey = false;
                colvarXtwpdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarXtwpdm);
                
                TableSchema.TableColumn colvarKcqcje = new TableSchema.TableColumn(schema);
                colvarKcqcje.ColumnName = "KCQCJE";
                colvarKcqcje.DataType = DbType.Decimal;
                colvarKcqcje.MaxLength = 0;
                colvarKcqcje.AutoIncrement = false;
                colvarKcqcje.IsNullable = true;
                colvarKcqcje.IsPrimaryKey = false;
                colvarKcqcje.IsForeignKey = false;
                colvarKcqcje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcqcje);
                
                TableSchema.TableColumn colvarKcrkje = new TableSchema.TableColumn(schema);
                colvarKcrkje.ColumnName = "KCRKJE";
                colvarKcrkje.DataType = DbType.Decimal;
                colvarKcrkje.MaxLength = 0;
                colvarKcrkje.AutoIncrement = false;
                colvarKcrkje.IsNullable = true;
                colvarKcrkje.IsPrimaryKey = false;
                colvarKcrkje.IsForeignKey = false;
                colvarKcrkje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcrkje);
                
                TableSchema.TableColumn colvarKcckje = new TableSchema.TableColumn(schema);
                colvarKcckje.ColumnName = "KCCKJE";
                colvarKcckje.DataType = DbType.Decimal;
                colvarKcckje.MaxLength = 0;
                colvarKcckje.AutoIncrement = false;
                colvarKcckje.IsNullable = true;
                colvarKcckje.IsPrimaryKey = false;
                colvarKcckje.IsForeignKey = false;
                colvarKcckje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcckje);
                
                TableSchema.TableColumn colvarKcykje = new TableSchema.TableColumn(schema);
                colvarKcykje.ColumnName = "KCYKJE";
                colvarKcykje.DataType = DbType.Decimal;
                colvarKcykje.MaxLength = 0;
                colvarKcykje.AutoIncrement = false;
                colvarKcykje.IsNullable = true;
                colvarKcykje.IsPrimaryKey = false;
                colvarKcykje.IsForeignKey = false;
                colvarKcykje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcykje);
                
                TableSchema.TableColumn colvarKcfkje = new TableSchema.TableColumn(schema);
                colvarKcfkje.ColumnName = "KCFKJE";
                colvarKcfkje.DataType = DbType.Decimal;
                colvarKcfkje.MaxLength = 0;
                colvarKcfkje.AutoIncrement = false;
                colvarKcfkje.IsNullable = true;
                colvarKcfkje.IsPrimaryKey = false;
                colvarKcfkje.IsForeignKey = false;
                colvarKcfkje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcfkje);
                
                TableSchema.TableColumn colvarKcthje = new TableSchema.TableColumn(schema);
                colvarKcthje.ColumnName = "KCTHJE";
                colvarKcthje.DataType = DbType.Decimal;
                colvarKcthje.MaxLength = 0;
                colvarKcthje.AutoIncrement = false;
                colvarKcthje.IsNullable = true;
                colvarKcthje.IsPrimaryKey = false;
                colvarKcthje.IsForeignKey = false;
                colvarKcthje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcthje);
                
                TableSchema.TableColumn colvarKcztje = new TableSchema.TableColumn(schema);
                colvarKcztje.ColumnName = "KCZTJE";
                colvarKcztje.DataType = DbType.Decimal;
                colvarKcztje.MaxLength = 0;
                colvarKcztje.AutoIncrement = false;
                colvarKcztje.IsNullable = true;
                colvarKcztje.IsPrimaryKey = false;
                colvarKcztje.IsForeignKey = false;
                colvarKcztje.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcztje);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["ErpNowthwin"].AddSchema("V_KCT06",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VKCT06()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public VKCT06(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public VKCT06(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public VKCT06(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Kckjnd")]
        [Bindable(true)]
        public decimal Kckjnd 
	    {
		    get
		    {
			    return GetColumnValue<decimal>("KCKJND");
		    }
            set 
		    {
			    SetColumnValue("KCKJND", value);
            }
        }
	      
        [XmlAttribute("Kckjyf")]
        [Bindable(true)]
        public decimal Kckjyf 
	    {
		    get
		    {
			    return GetColumnValue<decimal>("KCKJYF");
		    }
            set 
		    {
			    SetColumnValue("KCKJYF", value);
            }
        }
	      
        [XmlAttribute("Kcckdm")]
        [Bindable(true)]
        public string Kcckdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("KCCKDM");
		    }
            set 
		    {
			    SetColumnValue("KCCKDM", value);
            }
        }
	      
        [XmlAttribute("Xtwpdm")]
        [Bindable(true)]
        public string Xtwpdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("XTWPDM");
		    }
            set 
		    {
			    SetColumnValue("XTWPDM", value);
            }
        }
	      
        [XmlAttribute("Kcqcje")]
        [Bindable(true)]
        public decimal? Kcqcje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCQCJE");
		    }
            set 
		    {
			    SetColumnValue("KCQCJE", value);
            }
        }
	      
        [XmlAttribute("Kcrkje")]
        [Bindable(true)]
        public decimal? Kcrkje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCRKJE");
		    }
            set 
		    {
			    SetColumnValue("KCRKJE", value);
            }
        }
	      
        [XmlAttribute("Kcckje")]
        [Bindable(true)]
        public decimal? Kcckje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCCKJE");
		    }
            set 
		    {
			    SetColumnValue("KCCKJE", value);
            }
        }
	      
        [XmlAttribute("Kcykje")]
        [Bindable(true)]
        public decimal? Kcykje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCYKJE");
		    }
            set 
		    {
			    SetColumnValue("KCYKJE", value);
            }
        }
	      
        [XmlAttribute("Kcfkje")]
        [Bindable(true)]
        public decimal? Kcfkje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCFKJE");
		    }
            set 
		    {
			    SetColumnValue("KCFKJE", value);
            }
        }
	      
        [XmlAttribute("Kcthje")]
        [Bindable(true)]
        public decimal? Kcthje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCTHJE");
		    }
            set 
		    {
			    SetColumnValue("KCTHJE", value);
            }
        }
	      
        [XmlAttribute("Kcztje")]
        [Bindable(true)]
        public decimal? Kcztje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCZTJE");
		    }
            set 
		    {
			    SetColumnValue("KCZTJE", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Kckjnd = @"KCKJND";
            
            public static string Kckjyf = @"KCKJYF";
            
            public static string Kcckdm = @"KCCKDM";
            
            public static string Xtwpdm = @"XTWPDM";
            
            public static string Kcqcje = @"KCQCJE";
            
            public static string Kcrkje = @"KCRKJE";
            
            public static string Kcckje = @"KCCKJE";
            
            public static string Kcykje = @"KCYKJE";
            
            public static string Kcfkje = @"KCFKJE";
            
            public static string Kcthje = @"KCTHJE";
            
            public static string Kcztje = @"KCZTJE";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
