using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain{
    /// <summary>
    /// Strongly-typed collection for the VXTM22 class.
    /// </summary>
    [Serializable]
    public partial class VXTM22Collection : ReadOnlyList<VXTM22, VXTM22Collection>
    {        
        public VXTM22Collection() {}
    }
    /// <summary>
    /// This is  Read-only wrapper class for the V_XTM22 view.
    /// </summary>
    [Serializable]
    public partial class VXTM22 : ReadOnlyRecord<VXTM22>, IReadOnlyRecord
    {
    
	    #region Default Settings
	    protected static void SetSQLProps() 
	    {
		    GetTableSchema();
	    }
	    #endregion
        #region Schema Accessor
	    public static TableSchema.Table Schema
        {
            get
            {
                if (BaseSchema == null)
                {
                    SetSQLProps();
                }
                return BaseSchema;
            }
        }
    	
        private static void GetTableSchema() 
        {
            if(!IsSchemaInitialized)
            {
                //Schema declaration
                TableSchema.Table schema = new TableSchema.Table("V_XTM22", TableType.View, DataService.GetInstance("ErpNowthwin"));
                schema.Columns = new TableSchema.TableColumnCollection();
                schema.SchemaName = @"FYERP";
                //columns
                
                TableSchema.TableColumn colvarXtwpdm = new TableSchema.TableColumn(schema);
                colvarXtwpdm.ColumnName = "XTWPDM";
                colvarXtwpdm.DataType = DbType.String;
                colvarXtwpdm.MaxLength = 20;
                colvarXtwpdm.AutoIncrement = false;
                colvarXtwpdm.IsNullable = false;
                colvarXtwpdm.IsPrimaryKey = false;
                colvarXtwpdm.IsForeignKey = false;
                colvarXtwpdm.IsReadOnly = false;
                
                schema.Columns.Add(colvarXtwpdm);
                
                TableSchema.TableColumn colvarWpkcje = new TableSchema.TableColumn(schema);
                colvarWpkcje.ColumnName = "WPKCJE";
                colvarWpkcje.DataType = DbType.Decimal;
                colvarWpkcje.MaxLength = 0;
                colvarWpkcje.AutoIncrement = false;
                colvarWpkcje.IsNullable = true;
                colvarWpkcje.IsPrimaryKey = false;
                colvarWpkcje.IsForeignKey = false;
                colvarWpkcje.IsReadOnly = false;
                
                schema.Columns.Add(colvarWpkcje);
                
                TableSchema.TableColumn colvarKczksl = new TableSchema.TableColumn(schema);
                colvarKczksl.ColumnName = "KCZKSL";
                colvarKczksl.DataType = DbType.Decimal;
                colvarKczksl.MaxLength = 0;
                colvarKczksl.AutoIncrement = false;
                colvarKczksl.IsNullable = true;
                colvarKczksl.IsPrimaryKey = false;
                colvarKczksl.IsForeignKey = false;
                colvarKczksl.IsReadOnly = false;
                
                schema.Columns.Add(colvarKczksl);
                
                TableSchema.TableColumn colvarKcwpdj = new TableSchema.TableColumn(schema);
                colvarKcwpdj.ColumnName = "KCWPDJ";
                colvarKcwpdj.DataType = DbType.Decimal;
                colvarKcwpdj.MaxLength = 0;
                colvarKcwpdj.AutoIncrement = false;
                colvarKcwpdj.IsNullable = true;
                colvarKcwpdj.IsPrimaryKey = false;
                colvarKcwpdj.IsForeignKey = false;
                colvarKcwpdj.IsReadOnly = false;
                
                schema.Columns.Add(colvarKcwpdj);
                
                
                BaseSchema = schema;
                //add this schema to the provider
                //so we can query it later
                DataService.Providers["ErpNowthwin"].AddSchema("V_XTM22",schema);
            }
        }
        #endregion
        
        #region Query Accessor
	    public static Query CreateQuery()
	    {
		    return new Query(Schema);
	    }
	    #endregion
	    
	    #region .ctors
	    public VXTM22()
	    {
            SetSQLProps();
            SetDefaults();
            MarkNew();
        }
        public VXTM22(bool useDatabaseDefaults)
	    {
		    SetSQLProps();
		    if(useDatabaseDefaults)
		    {
				ForceDefaults();
			}
			MarkNew();
	    }
	    
	    public VXTM22(object keyID)
	    {
		    SetSQLProps();
		    LoadByKey(keyID);
	    }
    	 
	    public VXTM22(string columnName, object columnValue)
        {
            SetSQLProps();
            LoadByParam(columnName,columnValue);
        }
        
	    #endregion
	    
	    #region Props
	    
          
        [XmlAttribute("Xtwpdm")]
        [Bindable(true)]
        public string Xtwpdm 
	    {
		    get
		    {
			    return GetColumnValue<string>("XTWPDM");
		    }
            set 
		    {
			    SetColumnValue("XTWPDM", value);
            }
        }
	      
        [XmlAttribute("Wpkcje")]
        [Bindable(true)]
        public decimal? Wpkcje 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("WPKCJE");
		    }
            set 
		    {
			    SetColumnValue("WPKCJE", value);
            }
        }
	      
        [XmlAttribute("Kczksl")]
        [Bindable(true)]
        public decimal? Kczksl 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCZKSL");
		    }
            set 
		    {
			    SetColumnValue("KCZKSL", value);
            }
        }
	      
        [XmlAttribute("Kcwpdj")]
        [Bindable(true)]
        public decimal? Kcwpdj 
	    {
		    get
		    {
			    return GetColumnValue<decimal?>("KCWPDJ");
		    }
            set 
		    {
			    SetColumnValue("KCWPDJ", value);
            }
        }
	    
	    #endregion
    
	    #region Columns Struct
	    public struct Columns
	    {
		    
		    
            public static string Xtwpdm = @"XTWPDM";
            
            public static string Wpkcje = @"WPKCJE";
            
            public static string Kczksl = @"KCZKSL";
            
            public static string Kcwpdj = @"KCWPDJ";
            
	    }
	    #endregion
	    
	    
	    #region IAbstractRecord Members
        public new CT GetColumnValue<CT>(string columnName) {
            return base.GetColumnValue<CT>(columnName);
        }
        public object GetColumnValue(string columnName) {
            return base.GetColumnValue<object>(columnName);
        }
        #endregion
	    
    }
}
