using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for XSM04
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class XSM04Controller
    {
        // Preload our schema..
        XSM04 thisSchemaLoad = new XSM04();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public XSM04Collection FetchAll()
        {
            XSM04Collection coll = new XSM04Collection();
            Query qry = new Query(XSM04.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public XSM04Collection FetchByID(object Xslxdm)
        {
            XSM04Collection coll = new XSM04Collection().Where("XSLXDM", Xslxdm).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public XSM04Collection FetchByQuery(Query qry)
        {
            XSM04Collection coll = new XSM04Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Xslxdm)
        {
            return (XSM04.Delete(Xslxdm) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Xslxdm)
        {
            return (XSM04.Destroy(Xslxdm) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Xslxdm,string Xtdqdm)
        {
            Query qry = new Query(XSM04.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Xslxdm", Xslxdm).AND("Xtdqdm", Xtdqdm);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Xslxdm,string Xtdqdm,decimal? Xsyssj,string Xssydq,decimal? Xsglsl)
	    {
		    XSM04 item = new XSM04();
		    
            item.Xslxdm = Xslxdm;
            
            item.Xtdqdm = Xtdqdm;
            
            item.Xsyssj = Xsyssj;
            
            item.Xssydq = Xssydq;
            
            item.Xsglsl = Xsglsl;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Xslxdm,string Xtdqdm,decimal? Xsyssj,string Xssydq,decimal? Xsglsl)
	    {
		    XSM04 item = new XSM04();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Xslxdm = Xslxdm;
				
			item.Xtdqdm = Xtdqdm;
				
			item.Xsyssj = Xsyssj;
				
			item.Xssydq = Xssydq;
				
			item.Xsglsl = Xsglsl;
				
	        item.Save(UserName);
	    }
    }
}
