using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for XST191
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class XST191Controller
    {
        // Preload our schema..
        XST191 thisSchemaLoad = new XST191();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public XST191Collection FetchAll()
        {
            XST191Collection coll = new XST191Collection();
            Query qry = new Query(XST191.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public XST191Collection FetchByID(object Kcczxh)
        {
            XST191Collection coll = new XST191Collection().Where("KCCZXH", Kcczxh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public XST191Collection FetchByQuery(Query qry)
        {
            XST191Collection coll = new XST191Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Kcczxh)
        {
            return (XST191.Delete(Kcczxh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Kcczxh)
        {
            return (XST191.Destroy(Kcczxh) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(decimal Kcczxh,decimal Kckjyf,decimal Kckjnd,decimal Kcczhh)
        {
            Query qry = new Query(XST191.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Kcczxh", Kcczxh).AND("Kckjyf", Kckjyf).AND("Kckjnd", Kckjnd).AND("Kcczhh", Kcczhh);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(decimal Kcczxh,decimal Kckjyf,decimal Kckjnd,decimal Kcczhh,string Kcrkdh,decimal? Kcrkhh,DateTime? Xsshrq,decimal? Xssssl,string Kcshck)
	    {
		    XST191 item = new XST191();
		    
            item.Kcczxh = Kcczxh;
            
            item.Kckjyf = Kckjyf;
            
            item.Kckjnd = Kckjnd;
            
            item.Kcczhh = Kcczhh;
            
            item.Kcrkdh = Kcrkdh;
            
            item.Kcrkhh = Kcrkhh;
            
            item.Xsshrq = Xsshrq;
            
            item.Xssssl = Xssssl;
            
            item.Kcshck = Kcshck;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(decimal Kcczxh,decimal Kckjyf,decimal Kckjnd,decimal Kcczhh,string Kcrkdh,decimal? Kcrkhh,DateTime? Xsshrq,decimal? Xssssl,string Kcshck)
	    {
		    XST191 item = new XST191();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Kcczxh = Kcczxh;
				
			item.Kckjyf = Kckjyf;
				
			item.Kckjnd = Kckjnd;
				
			item.Kcczhh = Kcczhh;
				
			item.Kcrkdh = Kcrkdh;
				
			item.Kcrkhh = Kcrkhh;
				
			item.Xsshrq = Xsshrq;
				
			item.Xssssl = Xssssl;
				
			item.Kcshck = Kcshck;
				
	        item.Save(UserName);
	    }
    }
}
