using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
	/// <summary>
	/// Strongly-typed collection for the XTM121 class.
	/// </summary>
    [Serializable]
	public partial class XTM121Collection : ActiveList<XTM121, XTM121Collection>
	{	   
		public XTM121Collection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>XTM121Collection</returns>
		public XTM121Collection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                XTM121 o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the XTM121 table.
	/// </summary>
	[Serializable]
	public partial class XTM121 : ActiveRecord<XTM121>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public XTM121()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public XTM121(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public XTM121(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public XTM121(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("XTM121", TableType.Table, DataService.GetInstance("ErpNowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"FYERP";
				//columns
				
				TableSchema.TableColumn colvarXtwpjb = new TableSchema.TableColumn(schema);
				colvarXtwpjb.ColumnName = "XTWPJB";
				colvarXtwpjb.DataType = DbType.Decimal;
				colvarXtwpjb.MaxLength = 0;
				colvarXtwpjb.AutoIncrement = false;
				colvarXtwpjb.IsNullable = false;
				colvarXtwpjb.IsPrimaryKey = true;
				colvarXtwpjb.IsForeignKey = false;
				colvarXtwpjb.IsReadOnly = false;
				colvarXtwpjb.DefaultSetting = @"";
				colvarXtwpjb.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtwpjb);
				
				TableSchema.TableColumn colvarXtjbqs = new TableSchema.TableColumn(schema);
				colvarXtjbqs.ColumnName = "XTJBQS";
				colvarXtjbqs.DataType = DbType.Decimal;
				colvarXtjbqs.MaxLength = 0;
				colvarXtjbqs.AutoIncrement = false;
				colvarXtjbqs.IsNullable = true;
				colvarXtjbqs.IsPrimaryKey = false;
				colvarXtjbqs.IsForeignKey = false;
				colvarXtjbqs.IsReadOnly = false;
				colvarXtjbqs.DefaultSetting = @"";
				colvarXtjbqs.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjbqs);
				
				TableSchema.TableColumn colvarXtjbzz = new TableSchema.TableColumn(schema);
				colvarXtjbzz.ColumnName = "XTJBZZ";
				colvarXtjbzz.DataType = DbType.Decimal;
				colvarXtjbzz.MaxLength = 0;
				colvarXtjbzz.AutoIncrement = false;
				colvarXtjbzz.IsNullable = true;
				colvarXtjbzz.IsPrimaryKey = false;
				colvarXtjbzz.IsForeignKey = false;
				colvarXtjbzz.IsReadOnly = false;
				colvarXtjbzz.DefaultSetting = @"";
				colvarXtjbzz.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjbzz);
				
				TableSchema.TableColumn colvarXtjbyy = new TableSchema.TableColumn(schema);
				colvarXtjbyy.ColumnName = "XTJBYY";
				colvarXtjbyy.DataType = DbType.String;
				colvarXtjbyy.MaxLength = 20;
				colvarXtjbyy.AutoIncrement = false;
				colvarXtjbyy.IsNullable = true;
				colvarXtjbyy.IsPrimaryKey = false;
				colvarXtjbyy.IsForeignKey = false;
				colvarXtjbyy.IsReadOnly = false;
				colvarXtjbyy.DefaultSetting = @"";
				colvarXtjbyy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjbyy);
				
				TableSchema.TableColumn colvarXtjbsm = new TableSchema.TableColumn(schema);
				colvarXtjbsm.ColumnName = "XTJBSM";
				colvarXtjbsm.DataType = DbType.String;
				colvarXtjbsm.MaxLength = 60;
				colvarXtjbsm.AutoIncrement = false;
				colvarXtjbsm.IsNullable = true;
				colvarXtjbsm.IsPrimaryKey = false;
				colvarXtjbsm.IsForeignKey = false;
				colvarXtjbsm.IsReadOnly = false;
				colvarXtjbsm.DefaultSetting = @"";
				colvarXtjbsm.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjbsm);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["ErpNowthwin"].AddSchema("XTM121",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Xtwpjb")]
		[Bindable(true)]
		public decimal Xtwpjb 
		{
			get { return GetColumnValue<decimal>(Columns.Xtwpjb); }
			set { SetColumnValue(Columns.Xtwpjb, value); }
		}
		  
		[XmlAttribute("Xtjbqs")]
		[Bindable(true)]
		public decimal? Xtjbqs 
		{
			get { return GetColumnValue<decimal?>(Columns.Xtjbqs); }
			set { SetColumnValue(Columns.Xtjbqs, value); }
		}
		  
		[XmlAttribute("Xtjbzz")]
		[Bindable(true)]
		public decimal? Xtjbzz 
		{
			get { return GetColumnValue<decimal?>(Columns.Xtjbzz); }
			set { SetColumnValue(Columns.Xtjbzz, value); }
		}
		  
		[XmlAttribute("Xtjbyy")]
		[Bindable(true)]
		public string Xtjbyy 
		{
			get { return GetColumnValue<string>(Columns.Xtjbyy); }
			set { SetColumnValue(Columns.Xtjbyy, value); }
		}
		  
		[XmlAttribute("Xtjbsm")]
		[Bindable(true)]
		public string Xtjbsm 
		{
			get { return GetColumnValue<string>(Columns.Xtjbsm); }
			set { SetColumnValue(Columns.Xtjbsm, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(decimal varXtwpjb,decimal? varXtjbqs,decimal? varXtjbzz,string varXtjbyy,string varXtjbsm)
		{
			XTM121 item = new XTM121();
			
			item.Xtwpjb = varXtwpjb;
			
			item.Xtjbqs = varXtjbqs;
			
			item.Xtjbzz = varXtjbzz;
			
			item.Xtjbyy = varXtjbyy;
			
			item.Xtjbsm = varXtjbsm;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(decimal varXtwpjb,decimal? varXtjbqs,decimal? varXtjbzz,string varXtjbyy,string varXtjbsm)
		{
			XTM121 item = new XTM121();
			
				item.Xtwpjb = varXtwpjb;
			
				item.Xtjbqs = varXtjbqs;
			
				item.Xtjbzz = varXtjbzz;
			
				item.Xtjbyy = varXtjbyy;
			
				item.Xtjbsm = varXtjbsm;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn XtwpjbColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn XtjbqsColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn XtjbzzColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn XtjbyyColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn XtjbsmColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Xtwpjb = @"XTWPJB";
			 public static string Xtjbqs = @"XTJBQS";
			 public static string Xtjbzz = @"XTJBZZ";
			 public static string Xtjbyy = @"XTJBYY";
			 public static string Xtjbsm = @"XTJBSM";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
