using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for XTM13
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class XTM13Controller
    {
        // Preload our schema..
        XTM13 thisSchemaLoad = new XTM13();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public XTM13Collection FetchAll()
        {
            XTM13Collection coll = new XTM13Collection();
            Query qry = new Query(XTM13.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTM13Collection FetchByID(object Xtdqdm)
        {
            XTM13Collection coll = new XTM13Collection().Where("XTDQDM", Xtdqdm).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTM13Collection FetchByQuery(Query qry)
        {
            XTM13Collection coll = new XTM13Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Xtdqdm)
        {
            return (XTM13.Delete(Xtdqdm) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Xtdqdm)
        {
            return (XTM13.Destroy(Xtdqdm) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Xtdqdm,string Xtdqmc,string Xtmjbz,decimal? Xtdmcd)
	    {
		    XTM13 item = new XTM13();
		    
            item.Xtdqdm = Xtdqdm;
            
            item.Xtdqmc = Xtdqmc;
            
            item.Xtmjbz = Xtmjbz;
            
            item.Xtdmcd = Xtdmcd;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Xtdqdm,string Xtdqmc,string Xtmjbz,decimal? Xtdmcd)
	    {
		    XTM13 item = new XTM13();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Xtdqdm = Xtdqdm;
				
			item.Xtdqmc = Xtdqmc;
				
			item.Xtmjbz = Xtmjbz;
				
			item.Xtdmcd = Xtdmcd;
				
	        item.Save(UserName);
	    }
    }
}
