using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
	/// <summary>
	/// Strongly-typed collection for the XTM17 class.
	/// </summary>
    [Serializable]
	public partial class XTM17Collection : ActiveList<XTM17, XTM17Collection>
	{	   
		public XTM17Collection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>XTM17Collection</returns>
		public XTM17Collection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                XTM17 o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the XTM17 table.
	/// </summary>
	[Serializable]
	public partial class XTM17 : ActiveRecord<XTM17>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public XTM17()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public XTM17(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public XTM17(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public XTM17(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("XTM17", TableType.Table, DataService.GetInstance("ErpNowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"FYERP";
				//columns
				
				TableSchema.TableColumn colvarXtjsfs = new TableSchema.TableColumn(schema);
				colvarXtjsfs.ColumnName = "XTJSFS";
				colvarXtjsfs.DataType = DbType.String;
				colvarXtjsfs.MaxLength = 4;
				colvarXtjsfs.AutoIncrement = false;
				colvarXtjsfs.IsNullable = false;
				colvarXtjsfs.IsPrimaryKey = true;
				colvarXtjsfs.IsForeignKey = false;
				colvarXtjsfs.IsReadOnly = false;
				colvarXtjsfs.DefaultSetting = @"";
				colvarXtjsfs.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjsfs);
				
				TableSchema.TableColumn colvarXtjsmc = new TableSchema.TableColumn(schema);
				colvarXtjsmc.ColumnName = "XTJSMC";
				colvarXtjsmc.DataType = DbType.String;
				colvarXtjsmc.MaxLength = 40;
				colvarXtjsmc.AutoIncrement = false;
				colvarXtjsmc.IsNullable = true;
				colvarXtjsmc.IsPrimaryKey = false;
				colvarXtjsmc.IsForeignKey = false;
				colvarXtjsmc.IsReadOnly = false;
				colvarXtjsmc.DefaultSetting = @"";
				colvarXtjsmc.ForeignKeyTableName = "";
				schema.Columns.Add(colvarXtjsmc);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["ErpNowthwin"].AddSchema("XTM17",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Xtjsfs")]
		[Bindable(true)]
		public string Xtjsfs 
		{
			get { return GetColumnValue<string>(Columns.Xtjsfs); }
			set { SetColumnValue(Columns.Xtjsfs, value); }
		}
		  
		[XmlAttribute("Xtjsmc")]
		[Bindable(true)]
		public string Xtjsmc 
		{
			get { return GetColumnValue<string>(Columns.Xtjsmc); }
			set { SetColumnValue(Columns.Xtjsmc, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varXtjsfs,string varXtjsmc)
		{
			XTM17 item = new XTM17();
			
			item.Xtjsfs = varXtjsfs;
			
			item.Xtjsmc = varXtjsmc;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varXtjsfs,string varXtjsmc)
		{
			XTM17 item = new XTM17();
			
				item.Xtjsfs = varXtjsfs;
			
				item.Xtjsmc = varXtjsmc;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn XtjsfsColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn XtjsmcColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Xtjsfs = @"XTJSFS";
			 public static string Xtjsmc = @"XTJSMC";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
