using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for XTM22
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class XTM22Controller
    {
        // Preload our schema..
        XTM22 thisSchemaLoad = new XTM22();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public XTM22Collection FetchAll()
        {
            XTM22Collection coll = new XTM22Collection();
            Query qry = new Query(XTM22.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTM22Collection FetchByID(object Xttxhm)
        {
            XTM22Collection coll = new XTM22Collection().Where("XTTXHM", Xttxhm).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTM22Collection FetchByQuery(Query qry)
        {
            XTM22Collection coll = new XTM22Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Xttxhm)
        {
            return (XTM22.Delete(Xttxhm) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Xttxhm)
        {
            return (XTM22.Destroy(Xttxhm) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Xtzybz,DateTime? Bmscsj,string Scgydm,string Xtwpdm,string Xtwpmc,string Xtpzgg,string Xtwpxh,string Xttxhm,string Xtcwhs,string Kcjldw,string Cgjldw,string Xsjldw,string Cwjldw,string Kcpcgl,string Kcqsck,string Wpjyxm,decimal? Wphsjg,decimal? Wpryxq,decimal? Wpjcts,decimal? Wpxsdj,decimal? Wpkcje,string Wpmjbz,string Xttjbz,string Xtscsx,string Xtlybz,string Xtplgz,decimal? Xtplsl,decimal? Cgtqts,string Cgwldm,decimal? Wpcgdj,string Xtwphh,string Wpbcsh,string Wpgfsh,string Scjldw,string Xtdwbz,decimal? Xtscsh,decimal? Xtzhsh,string Wpxgsx,string Wpjylb,decimal? Wpcgsl,string Wpskbz,string Wpjybh,decimal? Cgkchs,decimal? Kcschs,string Xtcllb,decimal? Wpkzsl,string Xtqybz,string Xttybz,DateTime? Xtqyrq,DateTime? Xttyrq,string Wpkclb,decimal? Kczdkc,decimal? Kcaqkc,decimal? Kcdhdl,decimal? Kcrhfl,decimal? Kcdhbc,decimal? Kcpdzq,decimal? Kcpdwc,decimal? Kcjyqx)
	    {
		    XTM22 item = new XTM22();
		    
            item.Xtzybz = Xtzybz;
            
            item.Bmscsj = Bmscsj;
            
            item.Scgydm = Scgydm;
            
            item.Xtwpdm = Xtwpdm;
            
            item.Xtwpmc = Xtwpmc;
            
            item.Xtpzgg = Xtpzgg;
            
            item.Xtwpxh = Xtwpxh;
            
            item.Xttxhm = Xttxhm;
            
            item.Xtcwhs = Xtcwhs;
            
            item.Kcjldw = Kcjldw;
            
            item.Cgjldw = Cgjldw;
            
            item.Xsjldw = Xsjldw;
            
            item.Cwjldw = Cwjldw;
            
            item.Kcpcgl = Kcpcgl;
            
            item.Kcqsck = Kcqsck;
            
            item.Wpjyxm = Wpjyxm;
            
            item.Wphsjg = Wphsjg;
            
            item.Wpryxq = Wpryxq;
            
            item.Wpjcts = Wpjcts;
            
            item.Wpxsdj = Wpxsdj;
            
            item.Wpkcje = Wpkcje;
            
            item.Wpmjbz = Wpmjbz;
            
            item.Xttjbz = Xttjbz;
            
            item.Xtscsx = Xtscsx;
            
            item.Xtlybz = Xtlybz;
            
            item.Xtplgz = Xtplgz;
            
            item.Xtplsl = Xtplsl;
            
            item.Cgtqts = Cgtqts;
            
            item.Cgwldm = Cgwldm;
            
            item.Wpcgdj = Wpcgdj;
            
            item.Xtwphh = Xtwphh;
            
            item.Wpbcsh = Wpbcsh;
            
            item.Wpgfsh = Wpgfsh;
            
            item.Scjldw = Scjldw;
            
            item.Xtdwbz = Xtdwbz;
            
            item.Xtscsh = Xtscsh;
            
            item.Xtzhsh = Xtzhsh;
            
            item.Wpxgsx = Wpxgsx;
            
            item.Wpjylb = Wpjylb;
            
            item.Wpcgsl = Wpcgsl;
            
            item.Wpskbz = Wpskbz;
            
            item.Wpjybh = Wpjybh;
            
            item.Cgkchs = Cgkchs;
            
            item.Kcschs = Kcschs;
            
            item.Xtcllb = Xtcllb;
            
            item.Wpkzsl = Wpkzsl;
            
            item.Xtqybz = Xtqybz;
            
            item.Xttybz = Xttybz;
            
            item.Xtqyrq = Xtqyrq;
            
            item.Xttyrq = Xttyrq;
            
            item.Wpkclb = Wpkclb;
            
            item.Kczdkc = Kczdkc;
            
            item.Kcaqkc = Kcaqkc;
            
            item.Kcdhdl = Kcdhdl;
            
            item.Kcrhfl = Kcrhfl;
            
            item.Kcdhbc = Kcdhbc;
            
            item.Kcpdzq = Kcpdzq;
            
            item.Kcpdwc = Kcpdwc;
            
            item.Kcjyqx = Kcjyqx;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Xtzybz,DateTime? Bmscsj,string Scgydm,string Xtwpdm,string Xtwpmc,string Xtpzgg,string Xtwpxh,string Xttxhm,string Xtcwhs,string Kcjldw,string Cgjldw,string Xsjldw,string Cwjldw,string Kcpcgl,string Kcqsck,string Wpjyxm,decimal? Wphsjg,decimal? Wpryxq,decimal? Wpjcts,decimal? Wpxsdj,decimal? Wpkcje,string Wpmjbz,string Xttjbz,string Xtscsx,string Xtlybz,string Xtplgz,decimal? Xtplsl,decimal? Cgtqts,string Cgwldm,decimal? Wpcgdj,string Xtwphh,string Wpbcsh,string Wpgfsh,string Scjldw,string Xtdwbz,decimal? Xtscsh,decimal? Xtzhsh,string Wpxgsx,string Wpjylb,decimal? Wpcgsl,string Wpskbz,string Wpjybh,decimal? Cgkchs,decimal? Kcschs,string Xtcllb,decimal? Wpkzsl,string Xtqybz,string Xttybz,DateTime? Xtqyrq,DateTime? Xttyrq,string Wpkclb,decimal? Kczdkc,decimal? Kcaqkc,decimal? Kcdhdl,decimal? Kcrhfl,decimal? Kcdhbc,decimal? Kcpdzq,decimal? Kcpdwc,decimal? Kcjyqx)
	    {
		    XTM22 item = new XTM22();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Xtzybz = Xtzybz;
				
			item.Bmscsj = Bmscsj;
				
			item.Scgydm = Scgydm;
				
			item.Xtwpdm = Xtwpdm;
				
			item.Xtwpmc = Xtwpmc;
				
			item.Xtpzgg = Xtpzgg;
				
			item.Xtwpxh = Xtwpxh;
				
			item.Xttxhm = Xttxhm;
				
			item.Xtcwhs = Xtcwhs;
				
			item.Kcjldw = Kcjldw;
				
			item.Cgjldw = Cgjldw;
				
			item.Xsjldw = Xsjldw;
				
			item.Cwjldw = Cwjldw;
				
			item.Kcpcgl = Kcpcgl;
				
			item.Kcqsck = Kcqsck;
				
			item.Wpjyxm = Wpjyxm;
				
			item.Wphsjg = Wphsjg;
				
			item.Wpryxq = Wpryxq;
				
			item.Wpjcts = Wpjcts;
				
			item.Wpxsdj = Wpxsdj;
				
			item.Wpkcje = Wpkcje;
				
			item.Wpmjbz = Wpmjbz;
				
			item.Xttjbz = Xttjbz;
				
			item.Xtscsx = Xtscsx;
				
			item.Xtlybz = Xtlybz;
				
			item.Xtplgz = Xtplgz;
				
			item.Xtplsl = Xtplsl;
				
			item.Cgtqts = Cgtqts;
				
			item.Cgwldm = Cgwldm;
				
			item.Wpcgdj = Wpcgdj;
				
			item.Xtwphh = Xtwphh;
				
			item.Wpbcsh = Wpbcsh;
				
			item.Wpgfsh = Wpgfsh;
				
			item.Scjldw = Scjldw;
				
			item.Xtdwbz = Xtdwbz;
				
			item.Xtscsh = Xtscsh;
				
			item.Xtzhsh = Xtzhsh;
				
			item.Wpxgsx = Wpxgsx;
				
			item.Wpjylb = Wpjylb;
				
			item.Wpcgsl = Wpcgsl;
				
			item.Wpskbz = Wpskbz;
				
			item.Wpjybh = Wpjybh;
				
			item.Cgkchs = Cgkchs;
				
			item.Kcschs = Kcschs;
				
			item.Xtcllb = Xtcllb;
				
			item.Wpkzsl = Wpkzsl;
				
			item.Xtqybz = Xtqybz;
				
			item.Xttybz = Xttybz;
				
			item.Xtqyrq = Xtqyrq;
				
			item.Xttyrq = Xttyrq;
				
			item.Wpkclb = Wpkclb;
				
			item.Kczdkc = Kczdkc;
				
			item.Kcaqkc = Kcaqkc;
				
			item.Kcdhdl = Kcdhdl;
				
			item.Kcrhfl = Kcrhfl;
				
			item.Kcdhbc = Kcdhbc;
				
			item.Kcpdzq = Kcpdzq;
				
			item.Kcpdwc = Kcpdwc;
				
			item.Kcjyqx = Kcjyqx;
				
	        item.Save(UserName);
	    }
    }
}
