using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for XTT05
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class XTT05Controller
    {
        // Preload our schema..
        XTT05 thisSchemaLoad = new XTT05();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public XTT05Collection FetchAll()
        {
            XTT05Collection coll = new XTT05Collection();
            Query qry = new Query(XTT05.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTT05Collection FetchByID(object Xtxtlx)
        {
            XTT05Collection coll = new XTT05Collection().Where("XTXTLX", Xtxtlx).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public XTT05Collection FetchByQuery(Query qry)
        {
            XTT05Collection coll = new XTT05Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Xtxtlx)
        {
            return (XTT05.Delete(Xtxtlx) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Xtxtlx)
        {
            return (XTT05.Destroy(Xtxtlx) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Xtxtlx,string Xtyhzm,string Xtckdm,string Xtmkdm)
        {
            Query qry = new Query(XTT05.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Xtxtlx", Xtxtlx).AND("Xtyhzm", Xtyhzm).AND("Xtckdm", Xtckdm).AND("Xtmkdm", Xtmkdm);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Xtxtlx,string Xtyhzm,string Xtckdm,string Xtmkdm,string Xtxtdm)
	    {
		    XTT05 item = new XTT05();
		    
            item.Xtxtlx = Xtxtlx;
            
            item.Xtyhzm = Xtyhzm;
            
            item.Xtckdm = Xtckdm;
            
            item.Xtmkdm = Xtmkdm;
            
            item.Xtxtdm = Xtxtdm;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Xtxtlx,string Xtyhzm,string Xtckdm,string Xtmkdm,string Xtxtdm)
	    {
		    XTT05 item = new XTT05();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Xtxtlx = Xtxtlx;
				
			item.Xtyhzm = Xtyhzm;
				
			item.Xtckdm = Xtckdm;
				
			item.Xtmkdm = Xtmkdm;
				
			item.Xtxtdm = Xtxtdm;
				
	        item.Save(UserName);
	    }
    }
}
