using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for ZLM22
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ZLM22Controller
    {
        // Preload our schema..
        ZLM22 thisSchemaLoad = new ZLM22();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ZLM22Collection FetchAll()
        {
            ZLM22Collection coll = new ZLM22Collection();
            Query qry = new Query(ZLM22.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ZLM22Collection FetchByID(object Xttxhm)
        {
            ZLM22Collection coll = new ZLM22Collection().Where("XTTXHM", Xttxhm).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ZLM22Collection FetchByQuery(Query qry)
        {
            ZLM22Collection coll = new ZLM22Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Xttxhm)
        {
            return (ZLM22.Delete(Xttxhm) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Xttxhm)
        {
            return (ZLM22.Destroy(Xttxhm) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Xttxhm,string Zlxmdm)
        {
            Query qry = new Query(ZLM22.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Xttxhm", Xttxhm).AND("Zlxmdm", Zlxmdm);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Xttxhm,string Zlxmdm,string Zlllbz)
	    {
		    ZLM22 item = new ZLM22();
		    
            item.Xttxhm = Xttxhm;
            
            item.Zlxmdm = Zlxmdm;
            
            item.Zlllbz = Zlllbz;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Xttxhm,string Zlxmdm,string Zlllbz)
	    {
		    ZLM22 item = new ZLM22();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Xttxhm = Xttxhm;
				
			item.Zlxmdm = Zlxmdm;
				
			item.Zlllbz = Zlllbz;
				
	        item.Save(UserName);
	    }
    }
}
