using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
	/// <summary>
	/// Strongly-typed collection for the ZLT03 class.
	/// </summary>
    [Serializable]
	public partial class ZLT03Collection : ActiveList<ZLT03, ZLT03Collection>
	{	   
		public ZLT03Collection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>ZLT03Collection</returns>
		public ZLT03Collection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                ZLT03 o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the ZLT03 table.
	/// </summary>
	[Serializable]
	public partial class ZLT03 : ActiveRecord<ZLT03>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public ZLT03()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public ZLT03(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public ZLT03(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public ZLT03(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("ZLT03", TableType.Table, DataService.GetInstance("ErpNowthwin"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"FYERP";
				//columns
				
				TableSchema.TableColumn colvarZljybh = new TableSchema.TableColumn(schema);
				colvarZljybh.ColumnName = "ZLJYBH";
				colvarZljybh.DataType = DbType.String;
				colvarZljybh.MaxLength = 12;
				colvarZljybh.AutoIncrement = false;
				colvarZljybh.IsNullable = false;
				colvarZljybh.IsPrimaryKey = true;
				colvarZljybh.IsForeignKey = false;
				colvarZljybh.IsReadOnly = false;
				colvarZljybh.DefaultSetting = @"";
				colvarZljybh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarZljybh);
				
				TableSchema.TableColumn colvarZljyhh = new TableSchema.TableColumn(schema);
				colvarZljyhh.ColumnName = "ZLJYHH";
				colvarZljyhh.DataType = DbType.Decimal;
				colvarZljyhh.MaxLength = 0;
				colvarZljyhh.AutoIncrement = false;
				colvarZljyhh.IsNullable = false;
				colvarZljyhh.IsPrimaryKey = true;
				colvarZljyhh.IsForeignKey = false;
				colvarZljyhh.IsReadOnly = false;
				colvarZljyhh.DefaultSetting = @"";
				colvarZljyhh.ForeignKeyTableName = "";
				schema.Columns.Add(colvarZljyhh);
				
				TableSchema.TableColumn colvarZljylb = new TableSchema.TableColumn(schema);
				colvarZljylb.ColumnName = "ZLJYLB";
				colvarZljylb.DataType = DbType.String;
				colvarZljylb.MaxLength = 10;
				colvarZljylb.AutoIncrement = false;
				colvarZljylb.IsNullable = false;
				colvarZljylb.IsPrimaryKey = true;
				colvarZljylb.IsForeignKey = false;
				colvarZljylb.IsReadOnly = false;
				colvarZljylb.DefaultSetting = @"";
				colvarZljylb.ForeignKeyTableName = "";
				schema.Columns.Add(colvarZljylb);
				
				TableSchema.TableColumn colvarZljysl = new TableSchema.TableColumn(schema);
				colvarZljysl.ColumnName = "ZLJYSL";
				colvarZljysl.DataType = DbType.Decimal;
				colvarZljysl.MaxLength = 0;
				colvarZljysl.AutoIncrement = false;
				colvarZljysl.IsNullable = true;
				colvarZljysl.IsPrimaryKey = false;
				colvarZljysl.IsForeignKey = false;
				colvarZljysl.IsReadOnly = false;
				colvarZljysl.DefaultSetting = @"";
				colvarZljysl.ForeignKeyTableName = "";
				schema.Columns.Add(colvarZljysl);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["ErpNowthwin"].AddSchema("ZLT03",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Zljybh")]
		[Bindable(true)]
		public string Zljybh 
		{
			get { return GetColumnValue<string>(Columns.Zljybh); }
			set { SetColumnValue(Columns.Zljybh, value); }
		}
		  
		[XmlAttribute("Zljyhh")]
		[Bindable(true)]
		public decimal Zljyhh 
		{
			get { return GetColumnValue<decimal>(Columns.Zljyhh); }
			set { SetColumnValue(Columns.Zljyhh, value); }
		}
		  
		[XmlAttribute("Zljylb")]
		[Bindable(true)]
		public string Zljylb 
		{
			get { return GetColumnValue<string>(Columns.Zljylb); }
			set { SetColumnValue(Columns.Zljylb, value); }
		}
		  
		[XmlAttribute("Zljysl")]
		[Bindable(true)]
		public decimal? Zljysl 
		{
			get { return GetColumnValue<decimal?>(Columns.Zljysl); }
			set { SetColumnValue(Columns.Zljysl, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varZljybh,decimal varZljyhh,string varZljylb,decimal? varZljysl)
		{
			ZLT03 item = new ZLT03();
			
			item.Zljybh = varZljybh;
			
			item.Zljyhh = varZljyhh;
			
			item.Zljylb = varZljylb;
			
			item.Zljysl = varZljysl;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(string varZljybh,decimal varZljyhh,string varZljylb,decimal? varZljysl)
		{
			ZLT03 item = new ZLT03();
			
				item.Zljybh = varZljybh;
			
				item.Zljyhh = varZljyhh;
			
				item.Zljylb = varZljylb;
			
				item.Zljysl = varZljysl;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn ZljybhColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn ZljyhhColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ZljylbColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ZljyslColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Zljybh = @"ZLJYBH";
			 public static string Zljyhh = @"ZLJYHH";
			 public static string Zljylb = @"ZLJYLB";
			 public static string Zljysl = @"ZLJYSL";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
