using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace OracleDataDomain
{
    /// <summary>
    /// Controller class for ZLT02
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ZLT02Controller
    {
        // Preload our schema..
        ZLT02 thisSchemaLoad = new ZLT02();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ZLT02Collection FetchAll()
        {
            ZLT02Collection coll = new ZLT02Collection();
            Query qry = new Query(ZLT02.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ZLT02Collection FetchByID(object Zljybh)
        {
            ZLT02Collection coll = new ZLT02Collection().Where("ZLJYBH", Zljybh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ZLT02Collection FetchByQuery(Query qry)
        {
            ZLT02Collection coll = new ZLT02Collection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Zljybh)
        {
            return (ZLT02.Delete(Zljybh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Zljybh)
        {
            return (ZLT02.Destroy(Zljybh) == 1);
        }
        
        
        
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(string Zljybh,decimal Zljyhh)
        {
            Query qry = new Query(ZLT02.Schema);
            qry.QueryType = QueryType.Delete;
            qry.AddWhere("Zljybh", Zljybh).AND("Zljyhh", Zljyhh);
            qry.Execute();
            return (true);
        }        
       
    	
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Zljybh,decimal Zljyhh,string Sczsbh,string Xtwpks,string Xtwpys,decimal? Zljysl,decimal? Zlcjsl)
	    {
		    ZLT02 item = new ZLT02();
		    
            item.Zljybh = Zljybh;
            
            item.Zljyhh = Zljyhh;
            
            item.Sczsbh = Sczsbh;
            
            item.Xtwpks = Xtwpks;
            
            item.Xtwpys = Xtwpys;
            
            item.Zljysl = Zljysl;
            
            item.Zlcjsl = Zlcjsl;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(string Zljybh,decimal Zljyhh,string Sczsbh,string Xtwpks,string Xtwpys,decimal? Zljysl,decimal? Zlcjsl)
	    {
		    ZLT02 item = new ZLT02();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Zljybh = Zljybh;
				
			item.Zljyhh = Zljyhh;
				
			item.Sczsbh = Sczsbh;
				
			item.Xtwpks = Xtwpks;
				
			item.Xtwpys = Xtwpys;
				
			item.Zljysl = Zljysl;
				
			item.Zlcjsl = Zlcjsl;
				
	        item.Save(UserName);
	    }
    }
}
