using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Test1
{
    /// <summary>
    /// Controller class for T_PlanM
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TPlanMController
    {
        // Preload our schema..
        TPlanM thisSchemaLoad = new TPlanM();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TPlanMCollection FetchAll()
        {
            TPlanMCollection coll = new TPlanMCollection();
            Query qry = new Query(TPlanM.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TPlanMCollection FetchByID(object Scggdh)
        {
            TPlanMCollection coll = new TPlanMCollection().Where("SCGGDH", Scggdh).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TPlanMCollection FetchByQuery(Query qry)
        {
            TPlanMCollection coll = new TPlanMCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object Scggdh)
        {
            return (TPlanM.Delete(Scggdh) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object Scggdh)
        {
            return (TPlanM.Destroy(Scggdh) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string Sczsbh,string Scgcmc,DateTime? Scxdrq,DateTime? Sccjjq,string Scjhry,string Sczsbz,string Schtbh,string Scggdh,string Khddbh,string Sczsdl,int? Sczssl,string Sczszt,decimal? Scnlzy,string Status,bool? Deleted,string Wlbm,string Wlbmbz,string Wlbmdh,string PlanType,DateTime? Sctcrq,string Scfzxh,string Sckhxm,DateTime? Scfzjq,DateTime? Scztjq,DateTime? Scbzjq,DateTime? Scjhrq,DateTime? Ddjhrq,string StatusOld,string Ddhtbh,string Scgcmcreal)
	    {
		    TPlanM item = new TPlanM();
		    
            item.Sczsbh = Sczsbh;
            
            item.Scgcmc = Scgcmc;
            
            item.Scxdrq = Scxdrq;
            
            item.Sccjjq = Sccjjq;
            
            item.Scjhry = Scjhry;
            
            item.Sczsbz = Sczsbz;
            
            item.Schtbh = Schtbh;
            
            item.Scggdh = Scggdh;
            
            item.Khddbh = Khddbh;
            
            item.Sczsdl = Sczsdl;
            
            item.Sczssl = Sczssl;
            
            item.Sczszt = Sczszt;
            
            item.Scnlzy = Scnlzy;
            
            item.Status = Status;
            
            item.Deleted = Deleted;
            
            item.Wlbm = Wlbm;
            
            item.Wlbmbz = Wlbmbz;
            
            item.Wlbmdh = Wlbmdh;
            
            item.PlanType = PlanType;
            
            item.Sctcrq = Sctcrq;
            
            item.Scfzxh = Scfzxh;
            
            item.Sckhxm = Sckhxm;
            
            item.Scfzjq = Scfzjq;
            
            item.Scztjq = Scztjq;
            
            item.Scbzjq = Scbzjq;
            
            item.Scjhrq = Scjhrq;
            
            item.Ddjhrq = Ddjhrq;
            
            item.StatusOld = StatusOld;
            
            item.Ddhtbh = Ddhtbh;
            
            item.Scgcmcreal = Scgcmcreal;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int Planmid,string Sczsbh,string Scgcmc,DateTime? Scxdrq,DateTime? Sccjjq,string Scjhry,string Sczsbz,string Schtbh,string Scggdh,string Khddbh,string Sczsdl,int? Sczssl,string Sczszt,decimal? Scnlzy,string Status,bool? Deleted,string Wlbm,string Wlbmbz,string Wlbmdh,string PlanType,DateTime? Sctcrq,string Scfzxh,string Sckhxm,DateTime? Scfzjq,DateTime? Scztjq,DateTime? Scbzjq,DateTime? Scjhrq,DateTime? Ddjhrq,string StatusOld,string Ddhtbh,string Scgcmcreal)
	    {
		    TPlanM item = new TPlanM();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.Planmid = Planmid;
				
			item.Sczsbh = Sczsbh;
				
			item.Scgcmc = Scgcmc;
				
			item.Scxdrq = Scxdrq;
				
			item.Sccjjq = Sccjjq;
				
			item.Scjhry = Scjhry;
				
			item.Sczsbz = Sczsbz;
				
			item.Schtbh = Schtbh;
				
			item.Scggdh = Scggdh;
				
			item.Khddbh = Khddbh;
				
			item.Sczsdl = Sczsdl;
				
			item.Sczssl = Sczssl;
				
			item.Sczszt = Sczszt;
				
			item.Scnlzy = Scnlzy;
				
			item.Status = Status;
				
			item.Deleted = Deleted;
				
			item.Wlbm = Wlbm;
				
			item.Wlbmbz = Wlbmbz;
				
			item.Wlbmdh = Wlbmdh;
				
			item.PlanType = PlanType;
				
			item.Sctcrq = Sctcrq;
				
			item.Scfzxh = Scfzxh;
				
			item.Sckhxm = Sckhxm;
				
			item.Scfzjq = Scfzjq;
				
			item.Scztjq = Scztjq;
				
			item.Scbzjq = Scbzjq;
				
			item.Scjhrq = Scjhrq;
				
			item.Ddjhrq = Ddjhrq;
				
			item.StatusOld = StatusOld;
				
			item.Ddhtbh = Ddhtbh;
				
			item.Scgcmcreal = Scgcmcreal;
				
	        item.Save(UserName);
	    }
    }
}
